import {NextResponse} from "next/server";

type Message={role:"user"|"assistant"|"system";content:string};
const SYSTEM="You are AI Flash inside Long App by Phuc Long Center. Be concise, practical, and action-oriented. Respect the user's current language. Never pretend an external action succeeded unless the app confirms it.";

async function callOpenAI(messages:Message[]){const key=process.env.OPENAI_API_KEY;if(!key)return null;const r=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${key}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-5-mini",messages:[{role:"system",content:SYSTEM},...messages],temperature:.4})});if(!r.ok)throw new Error(`OpenAI ${r.status}`);const j=await r.json();return j.choices?.[0]?.message?.content||""}
async function callGemini(messages:Message[]){const key=process.env.GEMINI_API_KEY;if(!key)return null;const model=process.env.GEMINI_MODEL||"gemini-2.5-flash";const text=messages.map(m=>`${m.role}: ${m.content}`).join("\n");const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${encodeURIComponent(key)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:`${SYSTEM}\n${text}`}]}]})});if(!r.ok)throw new Error(`Gemini ${r.status}`);const j=await r.json();return j.candidates?.[0]?.content?.parts?.map((p:any)=>p.text||"").join("")||""}
async function callAnthropic(messages:Message[]){const key=process.env.ANTHROPIC_API_KEY;if(!key)return null;const r=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"content-type":"application/json","x-api-key":key,"anthropic-version":"2023-06-01"},body:JSON.stringify({model:process.env.ANTHROPIC_MODEL||"claude-sonnet-4-20250514",max_tokens:1200,system:SYSTEM,messages:messages.filter(m=>m.role!=="system").map(m=>({role:m.role==="assistant"?"assistant":"user",content:m.content}))})});if(!r.ok)throw new Error(`Anthropic ${r.status}`);const j=await r.json();return j.content?.map((p:any)=>p.text||"").join("")||""}

export async function POST(req:Request){try{const body=await req.json();const messages:Array<{role:string;body?:string;content?:string}>=Array.isArray(body?.messages)?body.messages:[];const normalized:Message[]=messages.slice(-24).map(m=>({role:m.role==="ai"||m.role==="assistant"?"assistant":"user",content:String(m.content||m.body||"")}));const preferred=(process.env.AI_FLASH_PROVIDER||"openai").toLowerCase();const order=preferred==="gemini"?[callGemini,callOpenAI,callAnthropic]:preferred==="anthropic"?[callAnthropic,callOpenAI,callGemini]:[callOpenAI,callGemini,callAnthropic];for(const fn of order){const text=await fn(normalized);if(text)return NextResponse.json({ok:true,text,provider:fn.name.replace("call","")})}return NextResponse.json({ok:false,code:"AI_PROVIDER_NOT_CONFIGURED",message:"AI Flash chưa được kết nối nhà cung cấp AI. Hãy cấu hình OPENAI_API_KEY, GEMINI_API_KEY hoặc ANTHROPIC_API_KEY trên Vercel."},{status:503})}catch(e:any){return NextResponse.json({ok:false,code:"AI_FLASH_ERROR",message:e?.message||"AI Flash request failed"},{status:500})}}
