"use client";

import {useEffect} from "react";

type ExecutorKind = "api" | "provider" | "device" | "job";
type RuntimeResult = {invocationId:string;actionId:string;state:"success"|"pending"|"gated"|"failed";resultCode:string;ownerCore?:string;coreReceipts?:Array<{core:string;status:string;receiptId:string;signature:string}>;chainVerified?:boolean;receipt?:{receiptId:string;signature:string};message?:string};
const KEY="long-action-evidence-ledger-v3";
const risky=/(payment|checkout|publish|delete|refund|take.live|go.live|open.sale|logout|thanh toán|hoàn tiền|xóa|đăng xuất|phát live)/i;
const local=/(back|close|open|select|choose|tab|menu|theme|language|filter|refresh|retry|view|toggle|quay|chọn|đóng|mở|xem)/i;
function slug(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,42)||"control"}
function normalizeActionIds(){const groups=new Map<string,HTMLButtonElement[]>();document.querySelectorAll<HTMLButtonElement>("button[data-action-id]").forEach(button=>{const base=button.dataset.actionBaseId||button.dataset.actionId!;button.dataset.actionBaseId=base;groups.set(base,[...(groups.get(base)||[]),button])});for(const[base,buttons]of groups){if(buttons.length===1){buttons[0].dataset.actionId=base;continue}const used=new Set<string>();buttons.forEach((button,index)=>{let id=`${base}.${slug(button.getAttribute("name")||button.textContent||String(index+1))}`;if(used.has(id))id=`${id}.${index+1}`;used.add(id);button.dataset.actionId=id})}window.dispatchEvent(new CustomEvent("long:action-contract-audit",{detail:{controls:document.querySelectorAll("button").length,unique:new Set([...document.querySelectorAll<HTMLButtonElement>("button")].map(x=>x.dataset.actionId).filter(Boolean)).size,missing:document.querySelectorAll("button:not([data-action-id])").length}}))}
function executionFor(signature:string):{executor:ExecutorKind;adapter:string}{if(local.test(signature))return{executor:"api",adapter:"internal-ui"};if(/connect|device|pair|tv|camera|microphone|display|cast|bluetooth|wifi/i.test(signature))return{executor:"device",adapter:"device-session"};if(/facebook|zalo|google|apple|oauth|payment|checkout|pay|provider/i.test(signature))return{executor:"provider",adapter:"provider-oauth"};if(/render|export|generate|flash|video|job/i.test(signature))return{executor:"job",adapter:"media-worker"};return{executor:"api",adapter:"domain-api"}}
function persist(result:RuntimeResult){try{const previous=JSON.parse(localStorage.getItem(KEY)||"[]");localStorage.setItem(KEY,JSON.stringify([...(Array.isArray(previous)?previous:[]),result].slice(-1000)))}catch{}}
async function executeAction(button:HTMLButtonElement,actionId:string,area:string,label:string){const invocationId=`${actionId}:${Date.now().toString(36)}:${crypto.randomUUID().slice(0,8)}`,target=executionFor(`${actionId}:${area}:${label}`);button.dataset.actionState="pending";const result=await fetch("/api/runtime/execute",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({invocationId,actionId,...target,input:{area,label,path:location.pathname}})}).then(async response=>({...(await response.json()),httpStatus:response.status})).catch(()=>({invocationId,actionId,state:"failed",resultCode:"RUNTIME_UNREACHABLE",message:"Không kết nối được runtime sáu lõi."})) as RuntimeResult;button.dataset.actionState=result.state;button.dataset.coreReceiptCount=String(result.coreReceipts?.length||0);button.dataset.coreChainVerified=String(result.chainVerified===true);persist(result);window.dispatchEvent(new CustomEvent("long:action-result",{detail:result}))}
export default function ActionRuntimeBridge(){useEffect(()=>{let scheduled=0;const schedule=()=>{cancelAnimationFrame(scheduled);scheduled=requestAnimationFrame(normalizeActionIds)};schedule();const observer=new MutationObserver(schedule);observer.observe(document.body,{subtree:true,childList:true});const onClick=(event:MouseEvent)=>{const button=(event.target as HTMLElement|null)?.closest<HTMLButtonElement>("button");if(!button||button.disabled||button.dataset.runtimeIgnore==="true")return;normalizeActionIds();const actionId=button.dataset.actionId;if(!actionId){event.preventDefault();event.stopPropagation();return}const area=button.dataset.runtimeArea||button.closest<HTMLElement>("[data-runtime-area]")?.dataset.runtimeArea||location.pathname,label=button.textContent?.trim()||button.getAttribute("aria-label")||"button",signature=`${actionId}:${area}:${label}`;if(risky.test(signature)&&button.dataset.runtimeIgnore!=="true"&&button.dataset.executorReceipt!=="verified"){event.preventDefault();event.stopPropagation()}void executeAction(button,actionId,area,label)};document.addEventListener("click",onClick,true);return()=>{observer.disconnect();cancelAnimationFrame(scheduled);document.removeEventListener("click",onClick,true)}},[]);return null}
