"use client";
import {useEffect} from "react";
type CoreId="long-scene"|"flash-flow"|"eventspace"|"media"|"long-ai"|"connection";
type ActionState="success"|"pending"|"gated"|"failed";
type Receipt={receiptId:string;actionId:string;executor:string;issuedAt:string;verified:boolean};
type SignalResult={invocationId:string;actionId:string;state:ActionState;resultCode:string;ownerCore:CoreId;coreTrace:Array<{core:CoreId;mode:"planned"|"pass-through"}>;createdAt:string;reason?:string;receipt?:Receipt};
const KEY="long-action-evidence-ledger-v2";
const risky=/(payment|checkout|publish|delete|refund|take.live|go.live|open.sale|logout|thanh toán|hoàn tiền|xóa|đăng xuất|phát live)/i;
const local=/(back|close|open|select|choose|tab|menu|theme|language|chọn lại|quay lại|đóng|mở)/i;
function slug(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,42)||"control"}
function owner(signature:string):CoreId{if(/scene|template|purchase|asset|store/i.test(signature))return"long-scene";if(/flash|pixel|flow/i.test(signature))return"flash-flow";if(/media|studio|camera|audio|video|mixer|live/i.test(signature))return"media";if(/(^|\W)ai(\W|$)/i.test(signature))return"long-ai";if(/connect|device|pair|tv|qr|login|auth/i.test(signature))return"connection";return"eventspace"}
function persist(result:SignalResult){try{const old=JSON.parse(localStorage.getItem(KEY)||"[]");localStorage.setItem(KEY,JSON.stringify([...(Array.isArray(old)?old:[]),result].slice(-1000)))}catch{}}
function normalizeActionIds(){const groups=new Map<string,HTMLButtonElement[]>();document.querySelectorAll<HTMLButtonElement>("button[data-action-id]").forEach(button=>{const base=button.dataset.actionBaseId||button.dataset.actionId!;button.dataset.actionBaseId=base;const list=groups.get(base)||[];list.push(button);groups.set(base,list)});for(const[base,buttons]of groups){if(buttons.length===1){buttons[0].dataset.actionId=base;continue}const used=new Set<string>();buttons.forEach((button,index)=>{let id=`${base}.${slug(button.getAttribute("name")||button.textContent||String(index+1))}`;if(used.has(id))id=`${id}.${index+1}`;used.add(id);button.dataset.actionId=id})}window.dispatchEvent(new CustomEvent("long:action-contract-audit",{detail:{controls:document.querySelectorAll("button").length,unique:new Set([...document.querySelectorAll<HTMLButtonElement>("button")].map(x=>x.dataset.actionId).filter(Boolean)).size,missing:document.querySelectorAll("button:not([data-action-id])").length}}))}
function navigationReceipt(actionId:string,issuedAt:string):Receipt{return{receiptId:`nav-${crypto.randomUUID()}`,actionId,executor:"navigation",issuedAt,verified:true}}
export default function ActionRuntimeBridge(){useEffect(()=>{let scheduled=0;const schedule=()=>{cancelAnimationFrame(scheduled);scheduled=requestAnimationFrame(normalizeActionIds)};schedule();const observer=new MutationObserver(schedule);observer.observe(document.body,{subtree:true,childList:true});const onClick=(event:MouseEvent)=>{const button=(event.target as HTMLElement|null)?.closest<HTMLButtonElement>("button");if(!button||button.disabled)return;normalizeActionIds();const actionId=button.dataset.actionId;const area=button.dataset.runtimeArea||button.closest<HTMLElement>("[data-runtime-area]")?.dataset.runtimeArea||location.pathname;const label=button.textContent?.trim()||"button";const signature=`${actionId||"missing"}:${area}:${label}`;const ownerCore=owner(signature);const createdAt=new Date().toISOString();const invocationId=`${actionId||"missing"}:${Date.now().toString(36)}:${crypto.randomUUID().slice(0,8)}`;let result:SignalResult;if(!actionId){event.preventDefault();event.stopPropagation();result={invocationId,actionId:"missing",state:"gated",resultCode:"MISSING_ACTION_ID",ownerCore,createdAt,reason:"Button has no Contract ID",coreTrace:[]}}else if(risky.test(signature)&&button.dataset.executorReceipt!=="verified"){event.preventDefault();event.stopPropagation();result={invocationId,actionId,state:"gated",resultCode:"VERIFIED_RECEIPT_REQUIRED",ownerCore,createdAt,reason:"Production action is blocked until its API/provider/device/job executor returns a verified receipt",coreTrace:[]}}else if(local.test(signature)){result={invocationId,actionId,state:"success",resultCode:"NAVIGATION_RECEIPT",ownerCore,createdAt,receipt:navigationReceipt(actionId,createdAt),coreTrace:[]}}else{result={invocationId,actionId,state:"pending",resultCode:"EXECUTOR_NOT_INVOKED",ownerCore,createdAt,reason:"No verified executor receipt; success is forbidden",coreTrace:[]}}result.coreTrace=(["eventspace","connection","long-scene","flash-flow","media","long-ai"]as CoreId[]).map(core=>({core,mode:core==="eventspace"||core===ownerCore?"planned":"pass-through"}));button.dataset.actionState=result.state;persist(result);window.dispatchEvent(new CustomEvent("long:action-result",{detail:result}))};document.addEventListener("click",onClick,true);return()=>{observer.disconnect();cancelAnimationFrame(scheduled);document.removeEventListener("click",onClick,true)}},[]);return null}
