"use client";

import {useEffect} from "react";

type CoreId="long-scene"|"flash-flow"|"eventspace"|"media"|"long-ai"|"connection";
type SignalResult={invocationId:string;actionId:string;state:"success"|"pending"|"gated";resultCode:string;ownerCore:CoreId;coreTrace:Array<{core:CoreId;mode:"active"|"pass-through"}>;createdAt:string;reason?:string;receipt?:{receiptId:string;source:"navigation";issuedAt:string}};
const KEY="long-action-evidence-ledger-v1";
const risky=/(payment|checkout|publish|delete|refund|take.live|go.live|open.sale|logout|thanh toán|hoàn tiền|xóa|đăng xuất|phát live)/i;
const local=/(back|close|open|select|choose|tab|menu|theme|language|chọn lại|quay lại|đóng|mở)/i;
function owner(signature:string):CoreId{if(/scene|template|purchase|asset|store/i.test(signature))return"long-scene";if(/flash|pixel|flow/i.test(signature))return"flash-flow";if(/media|studio|camera|audio|video|mixer|live/i.test(signature))return"media";if(/(^|\W)ai(\W|$)/i.test(signature))return"long-ai";if(/connect|device|pair|tv|qr|login|auth/i.test(signature))return"connection";return"eventspace"}
function persist(result:SignalResult){try{const old=JSON.parse(localStorage.getItem(KEY)||"[]");const next=[...(Array.isArray(old)?old:[]),result].slice(-500);localStorage.setItem(KEY,JSON.stringify(next))}catch{}}
export default function ActionRuntimeBridge(){useEffect(()=>{const onClick=(event:MouseEvent)=>{const button=(event.target as HTMLElement|null)?.closest<HTMLButtonElement>("button");if(!button||button.disabled)return;const actionId=button.dataset.actionId;const area=button.dataset.runtimeArea||button.closest<HTMLElement>("[data-runtime-area]")?.dataset.runtimeArea||location.pathname;const label=button.textContent?.trim()||"button";const signature=`${actionId||"missing"}:${area}:${label}`;const ownerCore=owner(signature);const createdAt=new Date().toISOString();const invocationId=`${actionId||"missing"}:${Date.now().toString(36)}:${crypto.randomUUID().slice(0,8)}`;let result:SignalResult;if(!actionId){event.preventDefault();event.stopPropagation();result={invocationId,actionId:"missing",state:"gated",resultCode:"MISSING_ACTION_ID",ownerCore,createdAt,reason:"Button has no Contract ID",coreTrace:[]}}else if(risky.test(signature)&&button.dataset.actionRiskApproved!=="true"){event.preventDefault();event.stopPropagation();result={invocationId,actionId,state:"gated",resultCode:"RECEIPT_REQUIRED",ownerCore,createdAt,reason:"Risky action requires explicit confirmation and verified executor receipt",coreTrace:[]}}else if(local.test(signature)){const receiptId=`nav-${crypto.randomUUID()}`;result={invocationId,actionId,state:"success",resultCode:"NAVIGATION_RECEIPT",ownerCore,createdAt,receipt:{receiptId,source:"navigation",issuedAt:createdAt},coreTrace:[]}}else{result={invocationId,actionId,state:"pending",resultCode:"COMMAND_ACCEPTED",ownerCore,createdAt,reason:"Awaiting executor receipt",coreTrace:[]}}result.coreTrace=(["eventspace","connection","long-scene","flash-flow","media","long-ai"] as CoreId[]).map(core=>({core,mode:core==="eventspace"||core==="connection"||core===ownerCore?"active":"pass-through"}));button.dataset.actionState=result.state;persist(result);window.dispatchEvent(new CustomEvent("long:action-result",{detail:result}))};document.addEventListener("click",onClick,true);return()=>document.removeEventListener("click",onClick,true)},[]);return null}
