"use client";
import {useEffect,useState} from "react";
import type {Lang} from "@/lib/navigation";
type Provider={provider:string;configured:boolean};type Session={provider:string;name:string;email?:string};
const names:Record<string,string>={google:"Google",facebook:"Facebook",zalo:"Zalo",apple:"Apple"};
export default function AuthLoginPanel({lang,onBack}:{lang:Lang;onBack:()=>void}){
 const[providers,setProviders]=useState<Provider[]>([]);const[session,setSession]=useState<Session|null>(null);const[loading,setLoading]=useState(true);const[message,setMessage]=useState("");const vi=lang==="vi";
 useEffect(()=>{fetch("/api/auth/providers",{cache:"no-store"}).then(response=>response.json()).then(data=>{setProviders(data.providers||[]);setSession(data.session||null)}).catch(()=>setMessage(vi?"Không đọc được cấu hình đăng nhập.":"Cannot load login configuration.")).finally(()=>setLoading(false))},[vi]);
 function login(provider:Provider){if(!provider.configured){setMessage(vi?`${names[provider.provider]} chưa được cấu hình Client ID/Secret trên máy chủ.`:`${names[provider.provider]} is not configured on the server.`);return}location.assign(`/api/auth/${provider.provider}/start`)}
 async function logout(){const response=await fetch("/api/auth/logout",{method:"POST"});if(response.ok){setSession(null);setMessage(vi?"Đã đăng xuất.":"Signed out.")}}
 return <section className="navWorkspace contentSurface authPanel" data-runtime-area="me.auth"><div className="workspaceCrumbs"><button data-action-id="pro.auth.back" type="button" className="backKey" onClick={onBack}>← Back</button><span className="crumbKey selected">{vi?"Đăng nhập nhanh":"Quick login"}</span></div>{session?<div className="authSession"><b>{vi?"Đã đăng nhập":"Signed in"}: {session.name}</b><span>{names[session.provider]}{session.email?` · ${session.email}`:""}</span><button data-action-id="pro.auth.logout" type="button" onClick={logout}>{vi?"Đăng xuất":"Sign out"}</button></div>:<><p>{vi?"Chọn nhà cung cấp. App chỉ nhận mã xác thực và tạo phiên bảo mật; không lưu mật khẩu mạng xã hội.":"Choose a provider. The app never stores your social password."}</p><div className="authProviderGrid">{providers.map(provider=><button data-action-id={`pro.auth.provider.${provider.provider}`} type="button" key={provider.provider} className={provider.configured?"priority":"providerDisabled"} onClick={()=>login(provider)}><b>{names[provider.provider]}</b><small>{provider.configured?(vi?"Sẵn sàng":"Ready"):(vi?"Chưa cấu hình":"Not configured")}</small></button>)}</div><button data-action-id="pro.auth.passkey" data-runtime-ignore="true" type="button" disabled className="providerDisabled"><b>Face ID / Passkey</b><small>{vi?"Kích hoạt sau lần đăng nhập đầu và đăng ký WebAuthn":"Available after first login and WebAuthn enrollment"}</small></button></>}{loading&&<div>{vi?"Đang kiểm tra cấu hình…":"Checking configuration…"}</div>}{message&&<div className="notice">{message}</div>}</section>
}
