"use client";
import {useEffect,useState} from "react";
import type {Lang} from "@/lib/navigation";
type Provider={provider:string;configured:boolean};type Session={provider:string;name:string;email?:string};
const names:Record<string,string>={google:"Google",facebook:"Facebook",zalo:"Zalo",apple:"Apple"};
export default function AuthLoginPanel({lang,onBack,initialMode="login"}:{lang:Lang;onBack:()=>void;initialMode?:"login"|"register"}){
 const[mode,setMode]=useState(initialMode);
 const[providers,setProviders]=useState<Provider[]>([]);const[session,setSession]=useState<Session|null>(null);const[loading,setLoading]=useState(true);const[message,setMessage]=useState("");const vi=lang==="vi";
 useEffect(()=>{fetch("/api/auth/providers",{cache:"no-store"}).then(response=>response.json()).then(data=>{setProviders(data.providers||[]);setSession(data.session||null)}).catch(()=>setMessage(vi?"Không đọc được cấu hình đăng nhập.":"Cannot load login configuration.")).finally(()=>setLoading(false))},[vi]);
 useEffect(()=>{if(new URLSearchParams(location.search).has("login_error"))setMessage(vi?"Không đăng nhập được. Hãy thử lại hoặc chọn tài khoản khác.":"Sign-in failed. Try again or choose another account.")},[vi]);
 function login(provider:Provider){if(!provider.configured){setMessage(vi?`${names[provider.provider]} hiện chưa khả dụng.`:`${names[provider.provider]} is not configured on the server.`);return}location.assign(`/api/auth/${provider.provider}/start`)}
 async function logout(){const response=await fetch("/api/auth/logout",{method:"POST"});if(response.ok){setSession(null);setMessage(vi?"Đã đăng xuất.":"Signed out.")}}
 return <section className="navWorkspace contentSurface authPanel" data-runtime-area="me.auth"><div className="workspaceCrumbs"><button data-action-id="pro.auth.back" type="button" className="backKey" onClick={onBack}>← Back</button><span className="crumbKey selected">{mode==="register"?(vi?"Đăng ký mới":"Create account"):(vi?"Đăng nhập nhanh":"Quick login")}</span></div>{session?<div className="authSession"><b>{vi?"Đã đăng nhập":"Signed in"}: {session.name}</b><span>{names[session.provider]}{session.email?` · ${session.email}`:""}</span><button data-action-id="pro.auth.logout" data-runtime-ignore="true" type="button" onClick={logout}>{vi?"Đăng xuất":"Sign out"}</button></div>:<><div className="authProviderGrid"><button data-action-id="pro.auth.mode.login" type="button" aria-pressed={mode==="login"} onClick={()=>setMode("login")}>{vi?"Đăng nhập":"Sign in"}</button><button data-action-id="pro.auth.mode.register" type="button" aria-pressed={mode==="register"} onClick={()=>setMode("register")}>{vi?"Đăng ký mới":"Create account"}</button></div><p>{mode==="register"?(vi?"Chọn tài khoản để tạo hồ sơ Long. Nếu đã có hồ sơ, bạn sẽ được đăng nhập.":"Choose an account to create your Long profile, or sign in if it exists."):(vi?"Chọn tài khoản đăng nhập.":"Choose your sign-in account.")}</p><div className="authProviderGrid">{providers.map(provider=><button data-action-id={`pro.auth.provider.${provider.provider}`} data-runtime-ignore="true" type="button" disabled={!provider.configured} key={provider.provider} className={provider.configured?"priority":"providerDisabled"} onClick={()=>login(provider)}><b>{names[provider.provider]}</b><small>{provider.configured?(vi?"Sẵn sàng":"Ready"):(vi?"Chưa khả dụng":"Not configured")}</small></button>)}</div><button data-action-id="pro.auth.passkey" data-runtime-ignore="true" type="button" disabled className="providerDisabled"><b>Face ID / Passkey</b><small>{vi?"Chưa khả dụng":"Available after first login and WebAuthn enrollment"}</small></button></>}{loading&&<div>{vi?"Đang kiểm tra cấu hình…":"Checking configuration…"}</div>}{message&&<div className="notice">{message}</div>}</section>
}
