"use client";
import {useEffect,useMemo,useState} from "react";
import {useEventSpace} from "@/components/EventSpaceProvider";
const video=["Preview","HDMI / DP","LED / Event Display","PXP / Multi Screen","Freeze","Black / Safety"],audio=["CH1","CH2","CH3","CH4","Main L/R","Monitor"],generic=["Tự động","Khuyến nghị","Tiêu chuẩn","Nâng cao"];
type Stage="READY"|"PENDING_RECEIPT"|"VALIDATED"|"ARMED"|"LIVE"|"GATED"|"FAILED";
export default function BroadcastControl({itemId,resetSignal=0}:{itemId:string;resetSignal?:number}){const[selected,setSelected]=useState(""),[stage,setStage]=useState<Stage>("READY"),[message,setMessage]=useState("");const{record}=useEventSpace();const list=useMemo(()=>itemId==="tv"?video:itemId==="audio"?audio:generic,[itemId]);useEffect(()=>{setSelected("");setStage("READY");setMessage("")},[itemId,resetSignal]);
 async function execute(action:"validate"|"arm"|"take-live"){setStage("PENDING_RECEIPT");const actionId=`pro.studio.${itemId}.${selected||"default"}.${action}`;const result=await fetch("/api/runtime/execute",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({invocationId:`${action}:${crypto.randomUUID()}`,actionId,executor:"device",adapter:itemId==="tv"?"display-output":"media-output",input:{selected}})}).then(r=>r.json()).catch(()=>({ok:false,code:"EXECUTOR_UNREACHABLE"}));if(!result.ok||!result.receipt?.signature){setStage("GATED");setMessage(result.code||"VERIFIED_DEVICE_RECEIPT_REQUIRED");record({area:"studio.broadcast",action:actionId,result:"gated-no-receipt",costClass:"local",ok:false});return}const next:Stage=action==="validate"?"VALIDATED":action==="arm"?"ARMED":"LIVE";setStage(next);setMessage(`Receipt ${result.receipt.receiptId}`);record({area:"studio.broadcast",action:actionId,result:next,costClass:"local",ok:true})}
 if(!selected)return <div className="treePanel" data-runtime-area="studio.broadcast"><div className="treeHead"><span>04</span><div><b>{itemId==="tv"?"Video Output / Event Display":itemId==="audio"?"Audio Mix":"Điều khiển"}</b><small>Chọn đầu ra cần điều khiển</small></div></div><div className="treeActions">{list.map(value=><button data-action-id={`pro.broadcast.${itemId}.${value.toLowerCase().replace(/[^a-z0-9]+/g,"-")}`} key={value} onClick={()=>setSelected(value)}><strong>{value}</strong><span>Chọn → Cây 5</span></button>)}</div></div>;
 return <div className="treePanel" data-runtime-area="studio.broadcast"><div className="treeHead"><span>05</span><div><b>{selected}</b><small>Không có receipt → không LIVE</small></div><button data-action-id={`pro.broadcast.${itemId}.back`} onClick={()=>setSelected("")}>↩ Cây 4</button></div><div className="displaySummary"><div><span>OUTPUT</span><b>{selected}</b></div><div><span>STATE</span><b>{stage}</b><small>{message}</small></div></div><div className="safeFlow"><button data-action-id={`pro.broadcast.${itemId}.validate`} data-runtime-ignore="true" onClick={()=>execute("validate")}>VALIDATE</button><button data-action-id={`pro.broadcast.${itemId}.arm`} data-runtime-ignore="true" disabled={stage!=="VALIDATED"} onClick={()=>execute("arm")}>ARM</button><button data-action-id={`pro.broadcast.${itemId}.take-live`} data-runtime-ignore="true" disabled={stage!=="ARMED"} onClick={()=>execute("take-live")}>TAKE LIVE</button></div>{stage==="GATED"&&<p className="safetyNote">Adapter thiết bị chưa cung cấp receipt xác minh được. Đầu ra chưa được phát.</p>}</div>}
