"use client";

import {useCallback,useEffect,useRef,useState} from "react";
import type {Lang} from "@/lib/navigation";
const tr=(lang:Lang,vi:string,en:string,zh:string)=>lang==="en"?en:lang==="zh"?zh:vi;
type Msg={id:string;display_name:string;role:string;kind:string;body?:string;attachment_url?:string;attachment_name?:string;created_at:string};
export default function ChatRoomWorkspace({lang}:{lang:Lang}){
 const[token,setToken]=useState("");const[memberId,setMemberId]=useState("");const[messages,setMessages]=useState<Msg[]>([]);const[text,setText]=useState("");const[status,setStatus]=useState("");const fileRef=useRef<HTMLInputElement|null>(null);
 const load=useCallback(async()=>{if(!token)return;const saved=localStorage.getItem(`long-event-member-${token}`)||"";setMemberId(saved);if(!saved){setStatus(tr(lang,"Hãy tham gia sự kiện trước rồi quay lại Chat room.","Join the event first, then return to Chat room.","请先参加活动，再返回聊天室。"));return}const response=await fetch(`/api/event/${encodeURIComponent(token)}/chat`,{cache:"no-store"});const data=await response.json();if(response.ok&&data.ok){setMessages(data.messages||[]);setStatus("")}else setStatus(data.error||"CHAT_UNAVAILABLE")},[token,lang]);
 useEffect(()=>{if(!token||!memberId)return;load();const timer=window.setInterval(load,3000);return()=>window.clearInterval(timer)},[token,memberId,load]);
 async function send(){const body=text.trim();if(!body||!token||!memberId)return;const response=await fetch(`/api/event/${encodeURIComponent(token)}/chat`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({memberId,body})});const data=await response.json();if(response.ok&&data.ok){setText("");await load()}else setStatus(data.error||"SEND_FAILED")}
 async function upload(file?:File){if(!file||!token||!memberId)return;const form=new FormData();form.append("file",file);form.append("memberId",memberId);const response=await fetch(`/api/event/${encodeURIComponent(token)}/chat/upload`,{method:"POST",body:form});const data=await response.json();setStatus(response.ok&&data.ok?tr(lang,"Đã nhận upload receipt.","Upload receipt received.","已收到上传凭证。"):data.error||"UPLOAD_FAILED");if(response.ok)await load()}
 return <section className="navWorkspace contentSurface chatWindow" data-runtime-area="studio.chat"><aside className="chatSidebar"><h3>Chat room</h3><label><span>{tr(lang,"Mã sự kiện/phòng","Event/room code","活动/房间代码")}</span><input value={token} onChange={event=>{setToken(event.target.value.trim());setMemberId("")}} placeholder="event token"/></label><button data-action-id="pro.chat.room.open" type="button" onClick={load}>{tr(lang,"Mở phòng","Open room","打开房间")}</button><nav><button data-action-id="pro.chat.members.view" type="button" onClick={()=>setStatus(tr(lang,"Danh sách thành viên lấy từ Presence khi phòng đã mở.","Members load from Presence after the room opens.","房间打开后从在线状态加载成员。"))}>{tr(lang,"Thành viên","Members","成员")}</button><button data-action-id="pro.chat.files.open" type="button" onClick={()=>fileRef.current?.click()}>{tr(lang,"Media / File","Media / File","媒体/文件")}</button></nav></aside><div className="chatMain"><header><div><b>{token||tr(lang,"Chưa chọn phòng","No room selected","未选择房间")}</b><span>{memberId?tr(lang,"Đã tham gia","Joined","已加入"):tr(lang,"Chưa tham gia","Not joined","未加入")}</span></div><button data-action-id="pro.chat.refresh" type="button" onClick={load}>{tr(lang,"Làm mới","Refresh","刷新")}</button></header><div className="chatTimeline" aria-live="polite">{messages.length?messages.map(message=><article key={message.id}><b>{message.display_name}<small>{message.role}</small></b>{message.kind==="file"?<a href={message.attachment_url} target="_blank" rel="noreferrer">📎 {message.attachment_name}</a>:<p>{message.body}</p>}<time>{new Date(message.created_at).toLocaleTimeString()}</time></article>):<div className="semanticEmpty">{tr(lang,"Chưa có tin nhắn.","No messages yet.","暂无消息。")}</div>}</div><div className="chatComposer integrated"><button data-action-id="pro.chat.attachment.choose" type="button" onClick={()=>fileRef.current?.click()}>＋</button><input ref={fileRef} hidden type="file" onChange={event=>upload(event.target.files?.[0])}/><textarea aria-label={tr(lang,"Tin nhắn","Message","消息")} value={text} onChange={event=>setText(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();send()}}} placeholder={tr(lang,"Nhập tin nhắn…","Type a message…","输入消息…")}/><button data-action-id="pro.chat.message.send" type="button" disabled={!text.trim()||!memberId} onClick={send}>{tr(lang,"Gửi","Send","发送")}</button></div>{status&&<div className="notice">{status}</div>}</div></section>
}
