"use client";
import {useEffect,useState} from "react";
import type {Lang} from "@/core/i18n";
type Candidate={id:string;name:string;kind:"provider"|"device";adapter:string;available:boolean;reason?:string};
type Status="discovering"|"idle"|"consent"|"connecting"|"connected"|"gated"|"error";
const tr=(lang:Lang,vi:string,en:string,zh:string)=>lang==="en"?en:lang==="zh"?zh:vi;
export default function ConnectionGateway({kind,lang}:{kind:string;lang:Lang}){const[candidates,setCandidates]=useState<Candidate[]>([]),[selected,setSelected]=useState<Candidate|null>(null),[status,setStatus]=useState<Status>("discovering"),[message,setMessage]=useState("");
 async function discover(){setStatus("discovering");setMessage("");const server=await fetch(`/api/connect/discovery?kind=${encodeURIComponent(kind)}`,{cache:"no-store"}).then(r=>r.json()).catch(()=>({ok:false,candidates:[]}));const local:Candidate[]=[];if(kind==="devices"&&navigator.mediaDevices?.enumerateDevices){const devices=await navigator.mediaDevices.enumerateDevices().catch(()=>[]);devices.forEach((d,i)=>local.push({id:`media-${d.deviceId||i}`,name:d.label||`${d.kind} ${i+1}`,kind:"device",adapter:"browser-media",available:!!d.deviceId,reason:d.deviceId?undefined:"permission-required"}))}setCandidates([...(server.candidates||[]),...local]);setStatus("idle")}
 useEffect(()=>{discover()},[kind]);
 function requestConnect(candidate:Candidate){setSelected(candidate);setStatus("consent");setMessage(tr(lang,`Bạn có đồng ý kết nối một chạm với “${candidate.name}” không?`,`Allow one-tap connection to “${candidate.name}”?`,`是否允许一键连接“${candidate.name}”？`))}
 async function confirm(){if(!selected)return;setStatus("connecting");const invocationId=`connect:${Date.now().toString(36)}:${crypto.randomUUID().slice(0,8)}`;const response=await fetch("/api/connect/execute",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({invocationId,actionId:`connect.${kind}.${selected.id}`,target:selected,consent:true})});const result=await response.json().catch(()=>({ok:false,code:"INVALID_RESPONSE"}));if(result.ok&&result.receipt?.signature){setStatus("connected");setMessage(`${selected.name} · ${result.receipt.receiptId}`);return}setStatus("gated");setMessage(result.message||result.code||tr(lang,"Chưa có adapter/receipt hợp lệ.","No valid adapter/receipt yet.","尚无有效适配器或回执。"))}
 return <section className="connectGateway" data-runtime-area={`connect.${kind}`}><div className="connectHead"><div><span>LONG CONNECT ENGINE</span><h2>{tr(lang,"Kết nối nhanh","Quick Connect","快速连接")}</h2></div><b className={status}>● {status.toUpperCase()}</b></div><p>{tr(lang,"Chỉ báo ĐÃ KẾT NỐI sau khi adapter trả receipt xác minh được.","CONNECTED appears only after a verifiable adapter receipt.","仅在适配器返回可验证回执后显示已连接。")}</p><button data-action-id={`pro.connect.${kind}.discover`} type="button" onClick={discover}>{tr(lang,"Tìm lại thiết bị/nhà cung cấp","Discover again","重新发现")}</button><div className="completionGrid">{candidates.map(item=><button data-action-id={`pro.connect.${kind}.${item.id}`} type="button" key={item.id} disabled={!item.available} onClick={()=>requestConnect(item)}><b>{item.name}</b><small>{item.available?tr(lang,"Sẵn sàng hỏi quyền","Ready for consent","可请求授权"):item.reason}</small></button>)}</div>{!candidates.length&&status!=="discovering"&&<div className="connectResult">{tr(lang,"Không tìm thấy nguồn kết nối. QR/manual fallback vẫn khả dụng.","No connection source found. QR/manual fallback remains available.","未发现连接来源，可使用二维码/手动回退。")}</div>}{status==="consent"&&<div className="connectConsent" role="dialog" aria-modal="true"><b>{message}</b><div><button data-action-id={`pro.connect.${kind}.cancel`} onClick={()=>setStatus("idle")}>{tr(lang,"Không","No","否")}</button><button data-action-id={`pro.connect.${kind}.confirm`} data-runtime-ignore="true" onClick={confirm}>{tr(lang,"Đồng ý kết nối","Allow connection","允许连接")}</button></div></div>}{["gated","error","connected"].includes(status)&&<div className={`connectResult ${status}`}><strong>{status==="connected"?"✓ CONNECTED":"! NOT CONNECTED"}</strong><span>{message}</span></div>}</section>}
