"use client";
import {useMemo,useState} from "react";
import type {Lang} from "@/core/i18n";
type Status="idle"|"connecting"|"connected"|"error";
const presets:Record<string,string[]>={ai:["OpenAI","Gemini","Claude","Grok","Custom AI"],apps:["YouTube / Video","Streaming App","Social App","Custom App"],devices:["Long TV","Mac / Desktop","Phone / Tablet","Custom Device"],storage:["Google Drive","Cloud Storage","Object Storage","Custom Storage"],wallet:["WalletConnect","Browser Wallet","Custom Wallet"],custom:["REST API","Webhook","OAuth 2.0","Custom Endpoint"]};
const copy={vi:{title:"Kết Nối",choose:"Chọn nguồn kết nối",provider:"Nhà cung cấp / thiết bị",link:"Link / Endpoint (nếu cần)",connect:"KẾT NỐI",success:"ĐÃ KẾT NỐI",retry:"Thử lại",guide:"Hướng dẫn từng bước",find:"Tìm nguồn kết nối",fix:"Sửa",healthy:"Healthy",hint:"Chọn preset Long đã cấu hình hoặc dán link/endpoint. Secret/API key phải được lưu phía server, không lưu ở giao diện."},en:{title:"Connect",choose:"Choose connection source",provider:"Provider / device",link:"Link / Endpoint (optional)",connect:"CONNECT",success:"CONNECTED",retry:"Retry",guide:"Step-by-step guide",find:"Find connection source",fix:"Fix",healthy:"Healthy",hint:"Choose a Long preset or paste a link/endpoint. Secrets/API keys must be stored server-side, never in the UI."},zh:{title:"连接",choose:"选择连接来源",provider:"服务商 / 设备",link:"链接 / Endpoint（可选）",connect:"连接",success:"已连接",retry:"重试",guide:"分步指南",find:"查找连接来源",fix:"修复",healthy:"Healthy",hint:"选择 Long 预设或粘贴链接/Endpoint。密钥/API Key 必须保存在服务端。"}} as const;
export default function ConnectionGateway({kind,lang}:{kind:string;lang:Lang}){const t=copy[lang];const list=presets[kind]||presets.custom;const[provider,setProvider]=useState(list[0]);const[endpoint,setEndpoint]=useState("");const[status,setStatus]=useState<Status>("idle");const[msg,setMsg]=useState("");const savedKey=`long-connect-${kind}`;const saved=useMemo(()=>typeof window!=="undefined"?localStorage.getItem(savedKey):null,[savedKey]);
 async function connect(){setStatus("connecting");setMsg("");await new Promise(r=>setTimeout(r,650));if(endpoint && !/^https?:\/\//i.test(endpoint)){setStatus("error");setMsg(lang==="vi"?"Link/endpoint chưa hợp lệ. Hãy bắt đầu bằng https://":"Invalid link/endpoint. Start with https://");return}const name=provider+(endpoint?` • ${new URL(endpoint).hostname}`:"");localStorage.setItem(savedKey,name);setStatus("connected");setMsg(name)}
 return <div className="connectGateway"><div className="connectHead"><div><span>LONG CONNECTION GATEWAY</span><h2>{t.title} · {kind.toUpperCase()}</h2></div><b className={status}>{status==="connected"?"● CONNECTED":status==="connecting"?"● CONNECTING":"○ READY"}</b></div><p>{t.hint}</p><div className="connectWizard"><label><span>1. {t.choose}</span><select value={provider} onChange={e=>{setProvider(e.target.value);setStatus("idle")}}>{list.map(x=><option key={x}>{x}</option>)}</select></label><label><span>2. {t.link}</span><input value={endpoint} onChange={e=>setEndpoint(e.target.value)} placeholder="https://…"/></label><button className="action" onClick={connect} disabled={status==="connecting"}>3. {status==="connecting"?"…":t.connect}</button></div>{status==="connected"&&<div className="connectResult success"><strong>✓ {t.success}</strong><span>{msg}</span><small>Status: {t.healthy}</small></div>}{status==="error"&&<div className="connectResult error"><strong>! {msg}</strong><div><button onClick={()=>setStatus("idle")}>{t.fix}</button><button>{t.guide}</button><button onClick={connect}>{t.retry}</button><button>{t.find}</button></div></div>}{status==="idle"&&saved&&<div className="connectResult"><small>{lang==="vi"?"Kết nối gần nhất":"Last connection"}</small><strong>{saved}</strong></div>}</div>}
