"use client";
import {useEffect,useState} from "react";
import ThemePicker from "@/components/ThemePicker";
import type {Lang} from "@/lib/navigation";

type Props={lang:Lang;onBack:()=>void};
const tr=(lang:Lang,vi:string,en:string,zh:string)=>lang==="en"?en:lang==="zh"?zh:vi;
const Crumbs=({lang,onBack,title}:{lang:Lang;onBack:()=>void;title:string})=><div className="workspaceCrumbs"><button type="button" className="backKey" onClick={onBack}>← Back</button><button type="button" className="crumbKey selected">{title}</button></div>;

export function AppearanceCenter({lang,onBack}:Props){return <section className="navWorkspace contentSurface"><Crumbs lang={lang} onBack={onBack} title={tr(lang,"Giao diện","Appearance","外观")}/><div className="completionPanel"><h3>{tr(lang,"Theme & hiển thị","Theme & display","主题与显示")}</h3><ThemePicker/><div className="completionGrid"><button type="button">Mobile</button><button type="button">Web · Auto fit</button><button type="button">TV · Safe area</button><button type="button">1920×1080</button><button type="button">720p / 1080p</button><button type="button">Font / Density</button></div><div className="endStatus"><b>END</b><span>{tr(lang,"Chọn theme được áp dụng ngay và lưu trên thiết bị.","Theme applies immediately and is saved on this device.","主题会立即应用并保存在此设备上。")}</span></div></div></section>}

export function SoundCenter({lang,onBack}:Props){return <section className="navWorkspace contentSurface"><Crumbs lang={lang} onBack={onBack} title={tr(lang,"Âm thanh","Sound","声音")}/><div className="completionPanel"><h3>{tr(lang,"Thiết bị & âm thanh hệ thống","Device & system audio","设备与系统音频")}</h3><p className="muted">{tr(lang,"Nhạc nền đã được loại bỏ khỏi Long App. Khu vực này chỉ quản lý micro, loa, monitoring và quyền âm thanh phục vụ Phòng Thu/Live.","Background music has been removed from Long App. This area only manages microphone, speaker, monitoring and audio permissions for Studio/Live.","Long App 已移除背景音乐。此区域仅管理演播室/直播所需的麦克风、扬声器、监听和音频权限。")}</p><div className="completionGrid"><button type="button">{tr(lang,"Micro mặc định","Default microphone","默认麦克风")}</button><button type="button">{tr(lang,"Loa / tai nghe","Speaker / headphones","扬声器/耳机")}</button><button type="button">{tr(lang,"Monitoring","Monitoring","监听")}</button><button type="button">{tr(lang,"Quyền Micro","Microphone permission","麦克风权限")}</button></div><div className="endStatus"><b>END</b><span>{tr(lang,"Không có nhạc nền hoặc playlist trong app.","No background music or playlist is included in the app.","应用内不包含背景音乐或播放列表。")}</span></div></div></section>}

export function PrivacyCenter({lang,onBack}:Props){const[k,setK]=useState(false);return <section className="navWorkspace contentSurface"><Crumbs lang={lang} onBack={onBack} title={tr(lang,"Quyền riêng tư","Privacy","隐私")}/><div className="completionPanel"><h3>{tr(lang,"Privacy Center","Privacy Center","隐私中心")}</h3><div className="completionGrid"><button type="button" onClick={()=>setK(v=>!v)} className={k?"priority":""}>{tr(lang,"Ưu tiên xử lý local","Prefer local processing","优先本地处理")}</button><button type="button">{tr(lang,"Quyền Camera/Micro","Camera/Mic permissions","摄像头/麦克风权限")}</button><button type="button">{tr(lang,"Dữ liệu AI & lịch sử","AI data & history","AI数据与历史")}</button><button type="button">{tr(lang,"Xuất dữ liệu","Export data","导出数据")}</button><button type="button">{tr(lang,"Xóa dữ liệu cục bộ","Clear local data","清除本地数据")}</button></div><button type="button" className="endCommit" onClick={()=>localStorage.setItem("long-privacy-local-first",k?"1":"0")}>{tr(lang,"Lưu quyền riêng tư · END","Save privacy · END","保存隐私设置 · END")}</button></div></section>}

export function SecurityCenter({lang,onBack}:Props){return <section className="navWorkspace contentSurface"><Crumbs lang={lang} onBack={onBack} title={tr(lang,"Đăng nhập & bảo mật","Login & Security","登录与安全")}/><div className="completionPanel"><h3>{tr(lang,"Ưu tiên đăng nhập","Login priority","登录优先级")}</h3><div className="completionGrid"><button type="button" className="priority">1 · Face ID / Biometrics</button><button type="button">2 · Google / Apple</button><button type="button">3 · Email / Phone / OTP</button><button type="button">{tr(lang,"Thiết bị đang đăng nhập","Active sessions","已登录设备")}</button><button type="button">{tr(lang,"Đăng xuất tất cả","Logout all","全部退出")}</button></div><a className="bossLoginLink" href="/boss/login">{tr(lang,"Boss Login · Google Authenticator","Boss Login · Google Authenticator","Boss 登录 · Google Authenticator")}</a><div className="endStatus"><b>END</b><span>{tr(lang,"Boss dùng luồng đăng nhập tách biệt với user.","Boss uses a separate authentication flow from users.","Boss 使用与普通用户分离的认证流程。")}</span></div></div></section>}

export function StickerStore({lang,onBack,mode}:{lang:Lang;onBack:()=>void;mode:"store"|"wallet"}){const[count,setCount]=useState(0);return <section className="navWorkspace contentSurface"><Crumbs lang={lang} onBack={onBack} title={mode==="store"?"Sticker Store":tr(lang,"Sticker của tôi","My Stickers","我的贴纸")}/><div className="completionPanel"><div className="stickerSummary"><b>{tr(lang,"Điểm Sticker","Sticker Points","贴纸积分")}</b><span>1,250</span></div><div className="stickerGrid">{["Long Mascot","Diamond","LIVE","Gift","Flash","Event"].map((x,i)=><button type="button" key={x} onClick={()=>setCount(count+1)}><span className="stickerEmoji">{["🤖","💎","🔴","🎁","⚡","🎫"][i]}</span><b>{x}</b><small>{mode==="store"?tr(lang,"Mua / Tặng","Buy / Gift","购买/赠送"):tr(lang,"Dùng sticker","Use sticker","使用贴纸")}</small></button>)}</div><div className="completionGrid"><button type="button">{tr(lang,"Bộ sticker sở hữu","Owned packs","已拥有贴纸包")}</button><button type="button">{tr(lang,"Lịch sử điểm","Points history","积分历史")}</button><button type="button">{tr(lang,"Tặng sticker","Gift sticker","赠送贴纸")}</button><button type="button">{tr(lang,"Gửi vào Chat/Live","Send to Chat/Live","发送到聊天/直播")}</button></div><div className="endStatus"><b>END</b><span>{tr(lang,`Đã thao tác ${count} lần. Giao dịch thật sẽ dùng backend Store/Points.`,`Actions: ${count}. Real transactions use Store/Points backend.`,`已操作 ${count} 次。真实交易使用 Store/Points 后端。`)}</span></div></div></section>}

export function PaymentCenter({lang,onBack}:Props){const[method,setMethod]=useState("vietqr");const[done,setDone]=useState(false);return <section className="navWorkspace contentSurface mode-pay"><Crumbs lang={lang} onBack={onBack} title={tr(lang,"Phương thức thanh toán","Payment Methods","支付方式")}/><div className="completionPanel"><div className="paymentMethods">{[["vietqr","VietQR / Chuyển khoản"],["momo","MoMo"],["zalopay","ZaloPay"],["card","Visa / Mastercard"],["apple","Apple Pay"],["google","Google Pay"],["cod","COD"]].map(([id,name])=><button type="button" key={id} className={method===id?"selected priority":""} onClick={()=>{setMethod(id);setDone(false)}}>{name}</button>)}</div><div className="paymentDetail"><b>{tr(lang,"Đã chọn","Selected","已选择")}: {method}</b><p>{tr(lang,"R2 hoàn thiện luồng UI/END. Giao dịch thật chỉ hoạt động sau khi cấu hình provider/API tương ứng.","R2 completes the UI/END flow. Real transactions require the matching provider/API configuration.","R2 完成 UI/END 流程；真实交易需配置相应支付服务/API。")}</p></div><button type="button" className="endCommit" onClick={()=>setDone(true)}>{done?"✓ END":tr(lang,"Xác nhận phương thức · END","Confirm method · END","确认支付方式 · END")}</button></div></section>}
