"use client";
import {useEffect,useRef,useState} from "react";
import type {Lang} from "@/lib/navigation";

type DeviceInfo={deviceId:string;label:string;kind:MediaDeviceKind};
export default function MediaConnectionPanel({lang,onBack,onDone}:{lang:Lang;onBack:()=>void;onDone:()=>void}){
 const videoRef=useRef<HTMLVideoElement|null>(null); const streamRef=useRef<MediaStream|null>(null);
 const[devices,setDevices]=useState<DeviceInfo[]>([]); const[selected,setSelected]=useState(""); const[status,setStatus]=useState<"idle"|"ready"|"live"|"error">("idle"); const[msg,setMsg]=useState("");
 const vi=lang==="vi", zh=lang==="zh";
 async function scan(){try{setMsg(""); setStatus("idle"); const s=await navigator.mediaDevices.getUserMedia({video:true,audio:false}); s.getTracks().forEach(t=>t.stop()); const all=await navigator.mediaDevices.enumerateDevices(); const list=all.filter(d=>d.kind==="videoinput").map(d=>({deviceId:d.deviceId,label:d.label||"Video input",kind:d.kind})); setDevices(list); setSelected(list[0]?.deviceId||""); setStatus("ready"); if(!list.length)setMsg(vi?"Không tìm thấy capture/camera. Hãy cắm thiết bị rồi thử lại.":zh?"未找到采集卡/摄像头。请连接设备后重试。":"No capture/camera input found. Connect a device and retry.");}catch(e){setStatus("error");setMsg(vi?"Trình duyệt chưa được cấp quyền Camera/Capture.":zh?"浏览器尚未获得摄像头/采集权限。":"Camera/Capture permission is required.")}}
 async function preview(){try{streamRef.current?.getTracks().forEach(t=>t.stop()); const s=await navigator.mediaDevices.getUserMedia({video:selected?{deviceId:{exact:selected}}:true,audio:false});streamRef.current=s;if(videoRef.current)videoRef.current.srcObject=s;setStatus("live");setMsg(vi?"Đã nhận tín hiệu video. Kiểm tra preview trước khi kết nối.":zh?"已收到视频信号。连接前请检查预览。":"Video signal received. Check preview before connecting.");}catch{setStatus("error");setMsg(vi?"Không mở được nguồn video đã chọn.":zh?"无法打开所选视频源。":"Unable to open the selected video source.")}}
 function disconnect(){streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;if(videoRef.current)videoRef.current.srcObject=null;setStatus("ready");setMsg(vi?"Đã ngắt preview.":zh?"预览已断开。":"Preview disconnected.")}
 useEffect(()=>()=>streamRef.current?.getTracks().forEach(t=>t.stop()),[]);
 return <section className="navWorkspace mediaConnectPanel"><div className="workspaceCrumbs"><button type="button" className="backKey" onClick={onBack}>← Back</button><button type="button" className="crumbKey selected">{vi?"Thiết bị":zh?"设备":"Devices"}</button><button type="button" className="crumbKey selected">Laptop</button><button type="button" className="crumbKey selected tree5Crumb">HDMI / Capture</button></div>
 <div className="functionalPanel"><div className="functionalHead"><div><span>LONG CONNECTION ENGINE</span><h2>HDMI / Capture</h2></div><b className={`statePill ${status}`}>{status.toUpperCase()}</b></div>
 <div className="functionalGrid"><button type="button" className="priority" onClick={scan}>{vi?"1. Quét thiết bị":zh?"1. 扫描设备":"1. Scan devices"}</button><label><span>{vi?"2. Chọn nguồn":zh?"2. 选择来源":"2. Select source"}</span><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">{vi?"Tự động":zh?"自动":"Automatic"}</option>{devices.map(d=><option key={d.deviceId} value={d.deviceId}>{d.label}</option>)}</select></label><button type="button" onClick={preview} disabled={status!=="ready"&&!selected}>{vi?"3. Test / Preview":zh?"3. 测试/预览":"3. Test / Preview"}</button><button type="button" onClick={disconnect}>{vi?"Ngắt":zh?"断开":"Disconnect"}</button></div>
 <div className="mediaPreview"><video ref={videoRef} autoPlay playsInline muted/><div><b>{vi?"Trạng thái tín hiệu":zh?"信号状态":"Signal status"}</b><span>{msg|| (vi?"Quét thiết bị để bắt đầu.":zh?"扫描设备以开始。":"Scan devices to begin.")}</span></div></div>
 <div className="endCommitRow"><button type="button" className="secondaryEnd" onClick={onBack}>{vi?"Chọn lại":zh?"重新选择":"Choose again"}</button><button type="button" className="endCommit" disabled={status!=="live"} onClick={onDone}>{vi?"Kết nối · END":zh?"连接 · END":"Connect · END"}</button></div></div></section>
}
