"use client";

import {useEffect,useRef,useState} from "react";
import type {Lang} from "@/lib/navigation";
const tr=(lang:Lang,vi:string,en:string,zh:string)=>lang==="en"?en:lang==="zh"?zh:vi;
type Channel={id:string;name:string;gain:number;pan:number;fader:number;mute:boolean;solo:boolean};
const initial:Channel[]=[1,2,3,4,5,6,7,8].map(value=>({id:`mic-${value}`,name:`Mic ${value}`,gain:50,pan:0,fader:70,mute:false,solo:false}));
export default function MixerConsolePanel({lang}:{lang:Lang}){
 const[channels,setChannels]=useState<Channel[]>(initial);const[devices,setDevices]=useState<MediaDeviceInfo[]>([]);const[selectedDevice,setSelectedDevice]=useState("");const[level,setLevel]=useState(0);const[message,setMessage]=useState("");const streamRef=useRef<MediaStream|null>(null);const rafRef=useRef<number|null>(null);
 useEffect(()=>()=>{streamRef.current?.getTracks().forEach(track=>track.stop());if(rafRef.current)cancelAnimationFrame(rafRef.current)},[]);
 function patch(id:string,key:keyof Channel,value:string|number|boolean){setChannels(list=>list.map(channel=>channel.id===id?{...channel,[key]:value}:channel))}
 async function connectMic(){try{streamRef.current?.getTracks().forEach(track=>track.stop());const stream=await navigator.mediaDevices.getUserMedia({audio:selectedDevice?{deviceId:{exact:selectedDevice}}:true});streamRef.current=stream;const list=await navigator.mediaDevices.enumerateDevices();setDevices(list.filter(device=>device.kind==="audioinput"));const context=new AudioContext();const analyser=context.createAnalyser();context.createMediaStreamSource(stream).connect(analyser);const values=new Uint8Array(analyser.frequencyBinCount);const tick=()=>{analyser.getByteFrequencyData(values);setLevel(Math.round(values.reduce((a,b)=>a+b,0)/Math.max(1,values.length)/255*100));rafRef.current=requestAnimationFrame(tick)};tick();setMessage(tr(lang,"Micro đang hoạt động trong phiên hiện tại.","Microphone is active for this session.","麦克风在当前会话中活动。"))}catch{setMessage(tr(lang,"Không thể mở micro hoặc quyền bị từ chối.","Cannot open microphone or permission denied.","无法打开麦克风或权限被拒绝。"))}}
 async function save(){const response=await fetch("/api/mixer/config",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({name:"Last used",deviceId:selectedDevice,channels})});const data=await response.json().catch(()=>({}));setMessage(response.ok&&data.receiptId?tr(lang,"Đã lưu cấu hình","Configuration saved","配置已保存"):data.error||tr(lang,"Đăng nhập để lưu preset.","Sign in to save the preset.","请登录以保存预设。"))}
 return <section className="navWorkspace contentSurface mixerConsole" data-runtime-area="studio.mixer"><div className="mixerHeader"><div><small>LONG MIXER CONSOLE</small><h2>{tr(lang,"Bàn Mix","Mixer Console","调音台")}</h2></div><div className="levelMeter"><i style={{height:`${level}%`}}/><span>{level}%</span></div></div><div className="mixerDeviceRow"><select aria-label={tr(lang,"Nguồn micro","Microphone source","麦克风源")} value={selectedDevice} onChange={event=>setSelectedDevice(event.target.value)}><option value="">{tr(lang,"Micro mặc định","Default microphone","默认麦克风")}</option>{devices.map(device=><option key={device.deviceId} value={device.deviceId}>{device.label||device.deviceId.slice(0,12)}</option>)}</select><button data-action-id="pro.mixer.input.micro.connect" type="button" onClick={connectMic}>{tr(lang,"Mở/kiểm tra Micro","Open/test microphone","打开/测试麦克风")}</button></div><div className="mixerChannels">{channels.map(channel=><article key={channel.id} className="mixerStrip"><h3>{channel.name}</h3><label><span>GAIN</span><input aria-label={`${channel.name} gain`} type="range" min="0" max="100" value={channel.gain} onChange={event=>patch(channel.id,"gain",Number(event.target.value))}/><b>{channel.gain}</b></label><label><span>PAN</span><input aria-label={`${channel.name} pan`} type="range" min="-50" max="50" value={channel.pan} onChange={event=>patch(channel.id,"pan",Number(event.target.value))}/><b>{channel.pan}</b></label><label className="fader"><span>FADER</span><input aria-label={`${channel.name} fader`} type="range" min="0" max="100" value={channel.fader} onChange={event=>patch(channel.id,"fader",Number(event.target.value))}/><b>{channel.fader}</b></label><div><button data-action-id={`pro.mixer.${channel.id}.mute`} type="button" className={channel.mute?"danger":""} onClick={()=>patch(channel.id,"mute",!channel.mute)}>MUTE</button><button data-action-id={`pro.mixer.${channel.id}.solo`} type="button" className={channel.solo?"priority":""} onClick={()=>patch(channel.id,"solo",!channel.solo)}>SOLO</button></div></article>)}</div><div className="mixerFooter"><button data-action-id="pro.mixer.preset.voice" type="button" onClick={()=>setChannels(initial.map(channel=>({...channel,gain:62,fader:76})))}>VOICE</button><button data-action-id="pro.mixer.preset.music" type="button" onClick={()=>setChannels(initial.map(channel=>({...channel,gain:45,fader:68})))}>MUSIC</button><button data-action-id="pro.mixer.preset.safe" type="button" onClick={()=>setChannels(initial.map(channel=>({...channel,gain:35,fader:55})))}>SAFE</button><button data-action-id="pro.mixer.config.save" type="button" className="endCommit" onClick={save}>{tr(lang,"Lưu cấu hình","Save configuration","保存配置")}</button></div>{message&&<div className="notice">{message}</div>}</section>
}
