"use client";
import {useMemo,useState} from "react";
import QRCode from "qrcode";

type Lang="vi"|"en"|"zh";
type Props={lang:Lang;section:string;activeId:string;activeLabel:string;actionId?:string;actionLabel?:string;selectedId:string;selectedLabel:string;onCancel:()=>void;onComplete:()=>void};
const tr=(l:Lang,vi:string,en:string,zh:string)=>l==="en"?en:l==="zh"?zh:vi;
const norm=(s:string)=>s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");

function Card({title,children}:{title:string;children:any}){return <div className="semanticCard"><b>{title}</b><div>{children}</div></div>}

export function semanticIntent(p:Pick<Props,"section"|"activeLabel"|"actionLabel"|"selectedLabel"|"activeId"|"actionId"|"selectedId">){
 const s=norm([p.section,p.activeId,p.activeLabel,p.actionId,p.actionLabel,p.selectedId,p.selectedLabel].filter(Boolean).join(" "));
 if(/tao qr|create qr|qr/.test(s) && /tao|create|save/.test(s)) return "qr-create";
 if(/quet qr|scan qr|check-in|checkin/.test(s)) return "qr-scan";
 if(/ung dung ngoai|external app/.test(s)) return "external-app";
 if(/1080p|4k|8k|video output|dau ra video|tv thuong|tv \/ man hinh|screen/.test(s)) return "display-output";
 if(/ai soat bill|quet bill|scan bill|bill/.test(s)) return "ai-bill";
 if(/ai soat ve|quet ve|scan ticket|ticket/.test(s) && /ai|quet|scan|qr|duplicate/.test(s)) return "ai-ticket";
 if(/ai ban hang|sales ai|ban hang/.test(s) && /ai|one click/.test(s)) return "ai-sales";
 if(/one click ai/.test(s)) return "one-click";
 if(/camera|micro|microphone|capture|hdmi|thiet bi|device/.test(s) && /ket noi|connect|scan|test|permission|camera|micro|capture|hdmi/.test(s)) return "device";
 if(/gain|trim|eq|compress|noise gate|pan|mute|solo|aux|main l\/r|audio/.test(s) && /studio\.mixer|ban mix|mixer|am thanh/.test(s)) return "audio-control";
 if(/anh sang|lighting|brightness|temperature|stage light|scene sync/.test(s)) return "lighting-control";
 if(/record|render|replay|clip|export|xu[aấ]t video/.test(s)) return "media-render";
 if(/upload|tai file|media san pham|product media|anh|video/.test(s) && /studio\.chat|store\.sales|media/.test(s)) return "media-upload";
 if(/tao thong bao|create notice|thong bao [0-9]|notice [0-9]|notification/.test(s)) return "event-notice";
 if(/quan ly qua tang|manage gifts|gift manager/.test(s)) return "gift-manage";
 if(/tao qua tang|khoi tao|chon mau qua|gift template|dieu kien nhan|claim rule|tao qr qua|create gift|quantity|so luong/.test(s) && /gift|qua tang|createGift|creategift/i.test([p.section,p.activeId,p.actionId,p.selectedId].join(" "))) return "gift-create";
 if(/tao room live|room cong khai|room rieng tu|room su kien|room thu|qr room|create live room|public room|private room|event room|test room/.test(s)) return "room-create";
 if(/dat ten phong|ten phong|name room|room name/.test(s)) return "room-name";
 if(/lower third|overlay|logo bug|dong ho|clock|banner|mascot/.test(s) && /studio|flash|effect|hieu ung|idle/.test(s)) return "graphics-overlay";
 if(/custom api|api tuy chinh/.test(s)) return "custom-api";
 if(/tim khach|lich su mua|theo khach|find customer|purchase history|by customer/.test(s)) return "customer-orders";
 if(/thong tin ca nhan|anh dai dien|lien he|personal info|avatar|contact/.test(s) && /me\.profile|profile|ho so/.test(s)) return "profile";
 if(/inventory|kho hang|nhap kho|xuat kho|kiem ke/.test(s)) return "inventory";
 if(/order|don hang|tra cuu|shipping|doi tra|ma don/.test(s)) return "orders";
 return "generic";
}

export default function SemanticSpecializedPanel(p:Props){
 const intent=useMemo(()=>semanticIntent(p),[p]);
 const [status,setStatus]=useState("");
 const [text,setText]=useState("");
 const [file,setFile]=useState<File|null>(null);
 const [qr,setQr]=useState("");
 const [level,setLevel]=useState(50);
 const [device,setDevice]=useState("");
 const [busy,setBusy]=useState(false);
 const title=p.selectedLabel;
 async function ai(prompt:string){setBusy(true);setStatus(tr(p.lang,"Đang xử lý…","Processing…","处理中…"));try{const r=await fetch('/api/ai/flash',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({messages:[{role:'user',body:prompt}]})});const j=await r.json().catch(()=>null);if(!r.ok||!j?.ok)throw new Error(j?.message||`HTTP ${r.status}`);setStatus(String(j.text||tr(p.lang,"Đã xử lý.","Processed.","已处理。")));}catch(e:any){setStatus(e?.message||tr(p.lang,"AI/provider chưa sẵn sàng.","AI/provider unavailable.","AI/提供商不可用。"));}finally{setBusy(false)}}
 async function makeQR(){if(!text.trim())return;try{setQr(await QRCode.toDataURL(text.trim(),{width:280,margin:2}));setStatus(tr(p.lang,"QR đã tạo. Kiểm tra rồi lưu/hoàn tất.","QR created. Review then save/complete.","二维码已创建，请检查后保存/完成。"));}catch(e:any){setStatus(e?.message||"QR error")}}
 async function scanDevices(){setBusy(true);setStatus(tr(p.lang,"Đang kiểm tra thiết bị/quyền…","Checking devices/permissions…","正在检查设备/权限…"));try{if(!navigator.mediaDevices?.enumerateDevices)throw new Error(tr(p.lang,"Trình duyệt không hỗ trợ liệt kê thiết bị.","Device enumeration is unsupported.","浏览器不支持设备枚举。"));const ds=await navigator.mediaDevices.enumerateDevices();const names=ds.filter(x=>x.kind==='videoinput'||x.kind==='audioinput').map((x,i)=>x.label||`${x.kind} ${i+1}`);setStatus(names.length?names.join(' · '):tr(p.lang,"Chưa thấy thiết bị. Có thể cần cấp quyền trước.","No device found. Permission may be required first.","未发现设备，可能需要先授权。"));}catch(e:any){setStatus(e?.message||"Device error")}finally{setBusy(false)}}
 const finish=()=>{setStatus(tr(p.lang,"✓ Hoàn tất · END","✓ Complete · END","✓ 完成 · END"));setTimeout(p.onComplete,500)};

 return <section className="navWorkspace semanticWorkspace">
  <div className="workspaceCrumbs"><button type="button" className="backKey" onClick={p.onCancel}>← Back</button><button type="button" className="crumbKey selected">{p.activeLabel}</button>{p.actionLabel&&<button type="button" className="crumbKey selected">{p.actionLabel}</button>}<button type="button" className="crumbKey selected tree5Crumb">{p.selectedLabel}</button></div>
  <div className="semanticHead"><div><small>FUNCTIONAL CONTENT · {intent.toUpperCase()}</small><h2>{title}</h2></div><span className="runtimeBadge">{tr(p.lang,"SẴN SÀNG","READY","就绪")}</span></div>
  {intent==="qr-create"&&<div className="semanticGrid"><Card title={tr(p.lang,"Nội dung QR","QR content","二维码内容")}><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={tr(p.lang,"Link, mã phiên, check-in, nội dung…","URL, session code, check-in, content…","链接、会话码、签到内容…")}/><button type="button" onClick={makeQR}>{tr(p.lang,"Tạo QR","Create QR","创建二维码")}</button></Card><Card title={tr(p.lang,"Preview","Preview","预览")}>{qr?<img className="qrPreview" src={qr} alt="QR preview"/>:<div className="semanticEmpty">{tr(p.lang,"QR sẽ hiện ở đây.","QR preview appears here.","二维码预览将显示在此。")}</div>}</Card></div>}
  {intent==="qr-scan"&&<div className="semanticGrid"><Card title={tr(p.lang,"Nguồn quét","Scan source","扫描来源")}><input type="file" accept="image/*" capture="environment" onChange={e=>setFile(e.target.files?.[0]||null)}/><input value={text} onChange={e=>setText(e.target.value)} placeholder={tr(p.lang,"Hoặc nhập mã/QR text","Or enter code/QR text","或输入码/二维码文本")}/></Card><Card title={tr(p.lang,"Kết quả","Result","结果")}><div className="semanticEmpty">{file?file.name:status||tr(p.lang,"Chọn ảnh QR hoặc nhập mã để kiểm tra.","Choose a QR image or enter a code.","选择二维码图片或输入代码。")}</div><button type="button" onClick={()=>setStatus(text||file?.name||tr(p.lang,"Chưa có dữ liệu.","No data.","无数据。"))}>{tr(p.lang,"Kiểm tra","Check","检查")}</button></Card></div>}
  {intent==="external-app"&&<div className="semanticGrid"><Card title={tr(p.lang,"Nguồn ứng dụng","Application source","应用来源")}><select value={device} onChange={e=>setDevice(e.target.value)}><option value="">{tr(p.lang,"Chọn nguồn","Choose source","选择来源")}</option><option>OBS / Virtual Camera</option><option>Browser Tab</option><option>NDI / SRT Bridge</option><option>Companion App</option></select><button type="button" onClick={()=>setStatus(device?tr(p.lang,`Đã chọn ${device}.`,`Selected ${device}.`,`已选择 ${device}。`):tr(p.lang,"Hãy chọn nguồn ứng dụng.","Choose an application source.","请选择应用来源。"))}>{tr(p.lang,"Quét / kiểm tra","Scan / Check","扫描/检查")}</button></Card><Card title={tr(p.lang,"Runtime","Runtime","运行时")}><div className="semanticEmpty">{status||tr(p.lang,"Web không tự nhìn thấy mọi app hệ thống. Nếu nguồn không xuất hiện, dùng Virtual Camera/Companion bridge.","The web app cannot discover every system app directly. Use Virtual Camera/Companion bridge when needed.","网页无法直接发现所有系统应用，必要时使用虚拟摄像头/伴随桥接。")}</div></Card></div>}
  {intent==="display-output"&&<div className="semanticGrid"><Card title={tr(p.lang,"Thông số đầu ra","Output format","输出格式")}><select value={device} onChange={e=>setDevice(e.target.value)}><option>1920×1080 · FHD</option><option>2560×1440 · QHD</option><option>3840×2160 · 4K UHD</option><option>4096×2160 · 4K DCI</option><option>7680×4320 · 8K UHD</option><option>Custom LED / Event Canvas</option></select><label>FPS <input type="range" min="24" max="60" value={level} onChange={e=>setLevel(+e.target.value)}/><span>{level}</span></label></Card><Card title={tr(p.lang,"Kiểm tra trước LIVE","Pre-live validation","直播前验证")}><div className="semanticSteps"><button type="button" onClick={()=>setStatus('TEST PATTERN ✓')}>Test Pattern</button><button type="button" onClick={()=>setStatus('VALIDATE ✓')}>Validate</button><button type="button" onClick={()=>setStatus('ARM ✓')}>ARM</button></div><div className="semanticEmpty">{status||tr(p.lang,"Auto Fit → Test Pattern → Validate → ARM → TAKE LIVE","Auto Fit → Test Pattern → Validate → ARM → TAKE LIVE","自动适配 → 测试图 → 验证 → ARM → TAKE LIVE")}</div></Card></div>}
  {intent==="ai-bill"&&<div className="semanticGrid"><Card title={tr(p.lang,"Bill / hóa đơn","Bill / invoice","账单/发票")}><input type="file" accept="image/*,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={tr(p.lang,"Ghi chú cần AI kiểm tra…","What should AI check?","需要AI检查什么…")}/><button type="button" disabled={busy} onClick={()=>ai(`Bạn là AI soát bill. Hãy kiểm tra dữ liệu sau và nêu lỗi/bất thường/nghi vấn. File: ${file?.name||'chưa có file'}. Ghi chú: ${text}`)}>{tr(p.lang,"Soát bill","Check bill","检查账单")}</button></Card><Card title={tr(p.lang,"Kết quả AI","AI result","AI结果")}><div className="semanticResult">{status||tr(p.lang,"Chọn bill rồi chạy kiểm tra.","Choose a bill then run the check.","选择账单后运行检查。")}</div></Card></div>}
  {intent==="ai-ticket"&&<div className="semanticGrid"><Card title={tr(p.lang,"Vé / QR","Ticket / QR","票/二维码")}><input type="file" accept="image/*,.pdf" capture="environment" onChange={e=>setFile(e.target.files?.[0]||null)}/><input value={text} onChange={e=>setText(e.target.value)} placeholder={tr(p.lang,"Mã vé / QR text","Ticket code / QR text","票码/二维码文本")}/><button type="button" disabled={busy} onClick={()=>ai(`Soát vé/check QR. File: ${file?.name||'không có'}. Mã: ${text}. Trả kết quả hợp lệ, trùng, lỗi hoặc cần kiểm tra thêm.`)}>{tr(p.lang,"Soát vé","Check ticket","验票")}</button></Card><Card title={tr(p.lang,"Kết quả","Result","结果")}><div className="semanticResult">{status||tr(p.lang,"Chưa có kết quả.","No result yet.","暂无结果。")}</div></Card></div>}
  {intent==="ai-sales"&&<div className="semanticGrid"><Card title={tr(p.lang,"Thông tin bán hàng","Sales brief","销售信息")}><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={tr(p.lang,"Sản phẩm, khách hàng, mục tiêu, giá…","Product, customer, goal, price…","商品、客户、目标、价格…")}/><button type="button" disabled={busy} onClick={()=>ai(`Bạn là AI Bán Hàng của Long App. Từ brief sau, hãy đề xuất sản phẩm/giá/cách chào hàng ngắn gọn và CTA: ${text}`)}>{tr(p.lang,"AI đề xuất","Generate sales suggestion","AI销售建议")}</button></Card><Card title={tr(p.lang,"Kết quả","Result","结果")}><div className="semanticResult">{status||tr(p.lang,"Nhập brief để AI xử lý.","Enter a brief for AI.","输入简报供AI处理。")}</div></Card></div>}
  {intent==="one-click"&&<div className="semanticGrid four"><Card title="AI Bán Hàng"><button type="button" onClick={()=>setStatus(tr(p.lang,"Chuyển tới AI Bán Hàng.","Open AI Sales.","打开AI销售。"))}>Open</button></Card><Card title="AI Soát Bill"><button type="button" onClick={()=>setStatus(tr(p.lang,"Chuyển tới AI Soát Bill.","Open AI Bill Check.","打开AI账单检查。"))}>Open</button></Card><Card title="AI Soát Vé"><button type="button" onClick={()=>setStatus(tr(p.lang,"Chuyển tới AI Soát Vé.","Open AI Ticket Check.","打开AI验票。"))}>Open</button></Card><Card title={tr(p.lang,"Chạy một chạm","Run one click","一键运行")}><button type="button" onClick={()=>setStatus(tr(p.lang,"Chọn một tác vụ AI cụ thể trước khi chạy.","Choose a specific AI task before running.","运行前请选择具体AI任务。"))}>RUN</button></Card></div>}
  {intent==="device"&&<div className="semanticGrid"><Card title={tr(p.lang,"Thiết bị","Devices","设备")}><button type="button" disabled={busy} onClick={scanDevices}>{tr(p.lang,"Quét thiết bị","Scan devices","扫描设备")}</button><button type="button" onClick={async()=>{try{const s=await navigator.mediaDevices.getUserMedia({video:true,audio:true});s.getTracks().forEach(t=>t.stop());setStatus(tr(p.lang,"Đã cấp quyền camera/micro.","Camera/mic permission granted.","已获得摄像头/麦克风权限。"))}catch(e:any){setStatus(e?.message||tr(p.lang,"Chưa được cấp quyền.","Permission denied.","权限被拒绝。"))}}}>{tr(p.lang,"Xin quyền Camera/Micro","Request Camera/Mic","请求摄像头/麦克风权限")}</button></Card><Card title={tr(p.lang,"Trạng thái","Status","状态")}><div className="semanticResult">{status||tr(p.lang,"Chưa kiểm tra runtime.","Runtime not checked yet.","尚未检查运行时。")}</div></Card></div>}
  {(intent==="audio-control"||intent==="lighting-control")&&<div className="semanticGrid"><Card title={title}><label>{tr(p.lang,"Mức điều chỉnh","Level","级别")} <input type="range" min="0" max="100" value={level} onChange={e=>setLevel(+e.target.value)}/><span>{level}</span></label><div className="presetRow"><button type="button" onClick={()=>setLevel(35)}>SAFE</button><button type="button" onClick={()=>setLevel(50)}>DEFAULT</button><button type="button" onClick={()=>setLevel(70)}>EVENT</button></div></Card><Card title={tr(p.lang,"Monitor/Test","Monitor/Test","监听/测试")}><button type="button" onClick={()=>setStatus(tr(p.lang,"Đã test cấu hình hiện tại.","Current setting tested.","当前设置已测试。"))}>Test / Preview</button><div className="semanticEmpty">{status}</div></Card></div>}
  {intent==="media-render"&&<div className="semanticGrid"><Card title={tr(p.lang,"Nguồn / nội dung","Source / content","来源/内容")}><input type="file" accept="video/*,image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/><select value={device} onChange={e=>setDevice(e.target.value)}><option>720p</option><option>1080p</option><option>4K</option></select></Card><Card title={tr(p.lang,"Render / Output","Render / Output","渲染/输出")}><div className="semanticEmpty">{file?.name||tr(p.lang,"Chưa chọn nội dung.","No content selected.","未选择内容。")}</div><button type="button" onClick={()=>setStatus(tr(p.lang,"Đã chuẩn bị tác vụ render/output.","Render/output task prepared.","渲染/输出任务已准备。"))}>{tr(p.lang,"Chuẩn bị","Prepare","准备")}</button></Card></div>}
  {intent==="media-upload"&&<div className="semanticGrid"><Card title={tr(p.lang,"Chọn media","Choose media","选择媒体")}><input type="file" multiple accept="image/*,video/*,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><div className="semanticEmpty">{file?.name||tr(p.lang,"Chưa chọn file.","No file selected.","未选择文件。")}</div></Card><Card title={tr(p.lang,"Mục đích","Destination","用途")}><select><option>{tr(p.lang,"Gắn vào nội dung hiện tại","Attach to current content","附加到当前内容")}</option><option>{tr(p.lang,"Lưu thư viện","Save to library","保存到媒体库")}</option></select></Card></div>}
  {intent==="event-notice"&&<div className="semanticGrid"><Card title={tr(p.lang,"Soạn thông báo","Compose notice","撰写通知")}><input value={device} onChange={e=>setDevice(e.target.value)} placeholder={tr(p.lang,"Tiêu đề thông báo","Notice title","通知标题")}/><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={tr(p.lang,"Nội dung thông báo…","Notice content…","通知内容…")}/><select><option>{tr(p.lang,"Tất cả người tham gia","All attendees","所有参与者")}</option><option>{tr(p.lang,"Người đã check-in","Checked-in users","已签到用户")}</option><option>{tr(p.lang,"Theo sự kiện hiện tại","Current event","当前活动")}</option></select></Card><Card title={tr(p.lang,"Preview / trạng thái","Preview / status","预览/状态")}><div className="semanticResult">{device||tr(p.lang,"Chưa có tiêu đề","No title yet","暂无标题")}
{text||tr(p.lang,"Chưa có nội dung","No content yet","暂无内容")}</div><button type="button" onClick={()=>setStatus(device.trim()&&text.trim()?tr(p.lang,"Thông báo hợp lệ, sẵn sàng đăng.","Notice is valid and ready to publish.","通知有效，可发布。"):tr(p.lang,"Cần tiêu đề và nội dung.","Title and content are required.","需要标题和内容。"))}>Preview</button></Card></div>}
  {intent==="gift-manage"&&<div className="semanticGrid"><Card title={tr(p.lang,"Quà tặng hiện có","Existing gifts","现有礼物")}><input value={text} onChange={e=>setText(e.target.value)} placeholder={tr(p.lang,"Tìm theo tên/mã quà","Search gift name/code","按名称/代码搜索")}/><button type="button" onClick={()=>setStatus(tr(p.lang,"Đang chờ dữ liệu quà tặng từ runtime/API. Nếu chưa có quà sẽ hiển thị Empty State.","Waiting for gift inventory from runtime/API. Empty inventory will show an Empty State.","等待运行时/API礼物数据；没有礼物时显示空状态。"))}>{tr(p.lang,"Tải danh sách","Load gifts","加载礼物")}</button></Card><Card title={tr(p.lang,"Trạng thái","Status","状态")}><div className="semanticResult">{status||tr(p.lang,"Không dùng dữ liệu mẫu giả.","No fake sample data is used.","不使用虚假样例数据。")}</div></Card></div>}
  {intent==="gift-create"&&<div className="semanticGrid"><Card title={tr(p.lang,"Thiết lập quà tặng","Gift setup","礼物设置")}><input value={device} onChange={e=>setDevice(e.target.value)} placeholder={tr(p.lang,"Tên quà tặng","Gift name","礼物名称")}/><select><option>{tr(p.lang,"Quà vật lý","Physical gift","实体礼物")}</option><option>{tr(p.lang,"Mã ưu đãi / voucher","Voucher / code","优惠券/代码")}</option><option>{tr(p.lang,"Sticker / digital gift","Sticker / digital gift","贴纸/数字礼物")}</option></select><label>{tr(p.lang,"Số lượng","Quantity","数量")} <input type="number" min="1" value={level} onChange={e=>setLevel(Math.max(1,+e.target.value||1))}/></label><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={tr(p.lang,"Điều kiện nhận: check-in, vé, mua hàng, mã mời…","Claim rule: check-in, ticket, purchase, invite code…","领取条件：签到、票、购买、邀请码…")}/></Card><Card title={tr(p.lang,"Kết quả","Result","结果")}><div className="semanticResult">{status||tr(p.lang,"Điền thông tin quà. QR chỉ được tạo sau khi quà có ID runtime.","Fill in gift details. QR is created only after a runtime gift ID exists.","填写礼物信息；仅在获得运行时礼物ID后创建二维码。")}</div><button type="button" onClick={()=>setStatus(device.trim()?tr(p.lang,`Sẵn sàng khởi tạo ${level} quà: ${device}.`,`Ready to create ${level} gift(s): ${device}.`,`准备创建 ${level} 个礼物：${device}。`):tr(p.lang,"Cần tên quà tặng.","Gift name is required.","需要礼物名称。"))}>{tr(p.lang,"Kiểm tra","Validate","验证")}</button></Card></div>}
  {intent==="room-create"&&<div className="semanticGrid"><Card title={tr(p.lang,"Cấu hình room","Room setup","房间设置")}><input value={text} onChange={e=>setText(e.target.value)} placeholder={tr(p.lang,"Tên room","Room name","房间名称")}/><select value={device} onChange={e=>setDevice(e.target.value)}><option value="public">{tr(p.lang,"Công khai","Public","公开")}</option><option value="private">{tr(p.lang,"Riêng tư","Private","私人")}</option><option value="event">{tr(p.lang,"Theo sự kiện","Event","活动")}</option><option value="test">{tr(p.lang,"Room thử","Test","测试")}</option></select></Card><Card title={tr(p.lang,"Preview","Preview","预览")}><div className="semanticResult">{text||tr(p.lang,"Room chưa đặt tên","Room has no name yet","房间尚未命名")} · {device||"public"}</div><button type="button" onClick={()=>setStatus(text.trim()?tr(p.lang,"Room hợp lệ, sẵn sàng tạo.","Room is valid and ready to create.","房间有效，可创建。"):tr(p.lang,"Hãy nhập tên room.","Enter a room name.","请输入房间名称。"))}>Test</button></Card></div>}
  {intent==="room-name"&&<div className="semanticGrid"><Card title={tr(p.lang,"Tên phòng","Room name","房间名称")}><input value={text} onChange={e=>setText(e.target.value)} placeholder={tr(p.lang,"Ví dụ: Sân khấu chính","Example: Main Stage","例如：主舞台")}/><input value={device} onChange={e=>setDevice(e.target.value)} placeholder={tr(p.lang,"Mã / tên sự kiện (tùy chọn)","Event code/name (optional)","活动代码/名称（可选）")}/></Card><Card title={tr(p.lang,"Preview","Preview","预览")}><div className="semanticResult">{text||tr(p.lang,"Chưa đặt tên","No name yet","尚未命名")}</div></Card></div>}
  {intent==="graphics-overlay"&&<div className="semanticGrid"><Card title={tr(p.lang,"Nội dung đồ họa","Graphic content","图形内容")}><input value={text} onChange={e=>setText(e.target.value)} placeholder={/clock|dong ho/.test(norm(title))?tr(p.lang,"Định dạng giờ / múi giờ","Time format / timezone","时间格式/时区"):tr(p.lang,"Tiêu đề / nội dung hiển thị","Title / display text","标题/显示文本")}/><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/><label>{tr(p.lang,"Opacity / mức","Opacity / level","透明度/级别")} <input type="range" min="0" max="100" value={level} onChange={e=>setLevel(+e.target.value)}/><span>{level}%</span></label></Card><Card title={tr(p.lang,"Preview","Preview","预览")}><div className="graphicPreview"><b>{text||title}</b><small>{file?.name||tr(p.lang,"Không có ảnh","No image","无图片")}</small></div><button type="button" onClick={()=>setStatus(tr(p.lang,"Đồ họa đã sẵn sàng để Apply/TAKE.","Graphic is ready to Apply/TAKE.","图形已准备好应用/TAKE。"))}>Preview</button></Card></div>}
  {intent==="custom-api"&&<div className="semanticGrid"><Card title="Custom API"><input value={text} onChange={e=>setText(e.target.value)} placeholder="https://api.example.com"/><select value={device} onChange={e=>setDevice(e.target.value)}><option>Bearer Token</option><option>API Key</option><option>OAuth</option><option>None</option></select><textarea placeholder={tr(p.lang,"Headers/scopes (không nhập secret trực tiếp ở đây)","Headers/scopes (do not enter secrets directly here)","Headers/scopes（不要在此直接输入密钥）")}/></Card><Card title={tr(p.lang,"Kiểm tra cấu hình","Configuration check","配置检查")}><div className="semanticResult">{status||tr(p.lang,"Secret phải lấy từ Environment Variables ở server.","Secrets must come from server-side Environment Variables.","密钥必须来自服务器环境变量。")}</div><button type="button" onClick={()=>setStatus(text.startsWith("http")?tr(p.lang,"Base URL hợp lệ về hình thức. Runtime sẽ kiểm tra kết nối.","Base URL format looks valid. Runtime will test connectivity.","Base URL格式有效；运行时将测试连接。") : tr(p.lang,"Base URL chưa hợp lệ.","Base URL is invalid.","Base URL无效。"))}>Validate</button></Card></div>}
  {intent==="customer-orders"&&<div className="semanticGrid"><Card title={tr(p.lang,"Tìm khách","Find customer","查找客户")}><input value={text} onChange={e=>setText(e.target.value)} placeholder={tr(p.lang,"Tên / SĐT / email / mã khách","Name / phone / email / customer ID","姓名/电话/邮箱/客户ID")}/><button type="button" onClick={()=>setStatus(text?tr(p.lang,"Đã nhận tiêu chí. Đang chờ dữ liệu khách/đơn từ runtime API.","Criteria accepted. Waiting for customer/order data from runtime API.","已接收条件，等待运行时API客户/订单数据。") : tr(p.lang,"Nhập thông tin khách cần tìm.","Enter customer search data.","请输入客户搜索信息。"))}>{tr(p.lang,"Tìm khách","Find","查找")}</button></Card><Card title={tr(p.lang,"Lịch sử mua","Purchase history","购买历史")}><div className="semanticResult">{status||tr(p.lang,"Không hiển thị lịch sử mẫu. Không có dữ liệu sẽ trả Empty State.","No sample history is shown. Missing data returns an Empty State.","不显示样例历史；无数据时返回空状态。")}</div></Card></div>}
  {intent==="profile"&&<div className="semanticGrid"><Card title={tr(p.lang,"Hồ sơ","Profile","资料")}><input value={device} onChange={e=>setDevice(e.target.value)} placeholder={tr(p.lang,"Tên hiển thị","Display name","显示名称")}/><input value={text} onChange={e=>setText(e.target.value)} placeholder={tr(p.lang,"Email / điện thoại / liên hệ","Email / phone / contact","邮箱/电话/联系方式")}/><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></Card><Card title={tr(p.lang,"Trạng thái","Status","状态")}><div className="semanticResult">{status||tr(p.lang,"Dữ liệu hồ sơ thật sẽ được nạp theo user/session.","Live profile data loads from the user/session.","真实资料将按用户/会话加载。")}</div></Card></div>}
  {(intent==="inventory"||intent==="orders")&&<div className="semanticGrid"><Card title={tr(p.lang,"Tra cứu / dữ liệu","Lookup / data","查询/数据")}><input value={text} onChange={e=>setText(e.target.value)} placeholder={intent==='inventory'?tr(p.lang,"SKU, mã hàng, danh mục…","SKU, item code, category…","SKU、货号、类别…"):tr(p.lang,"Mã đơn, khách hàng…","Order code, customer…","订单号、客户…")}/><button type="button" onClick={()=>setStatus(text?tr(p.lang,"Đã nhận tiêu chí. Runtime/API sẽ trả dữ liệu thật.","Criteria accepted. Runtime/API will return live data.","已接收条件，运行时/API将返回真实数据。") : tr(p.lang,"Nhập tiêu chí tra cứu.","Enter lookup criteria.","请输入查询条件。"))}>{tr(p.lang,"Tra cứu","Lookup","查询")}</button></Card><Card title={tr(p.lang,"Kết quả","Result","结果")}><div className="semanticResult">{status||tr(p.lang,"Không có dữ liệu mẫu giả. Khi runtime trả rỗng sẽ hiển thị Empty State.","No fake sample data. Runtime emptiness will show an Empty State.","不显示虚假样例数据；运行时为空时显示空状态。")}</div></Card></div>}
  {intent==="generic"&&<div className="semanticGrid"><Card title={tr(p.lang,"Tác vụ","Task","任务")}><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={tr(p.lang,"Nhập dữ liệu/tùy chọn cần thiết cho tác vụ này…","Enter the data/options required for this task…","输入此任务所需的数据/选项…")}/><button type="button" onClick={()=>setStatus(tr(p.lang,"Đã kiểm tra dữ liệu đầu vào. Có thể hoàn tất.","Input checked. Ready to complete.","输入已检查，可以完成。"))}>Test / Preview</button></Card><Card title={tr(p.lang,"Trạng thái runtime","Runtime status","运行时状态")}><div className="semanticResult">{status||tr(p.lang,"Nếu tác vụ cần API/quyền/dữ liệu thiết bị, trạng thái sẽ hiển thị tại đây thay vì màn rỗng.","API/permission/device dependencies appear here instead of a blank screen.","API/权限/设备依赖将在此显示，而不是空白页面。")}</div></Card></div>}
  {status&&intent!=="ai-bill"&&intent!=="ai-ticket"&&intent!=="ai-sales"&&<div className="semanticStatus">{status}</div>}
  <div className="semanticEndRow"><button type="button" className="secondaryEnd" onClick={p.onCancel}>{tr(p.lang,"Chọn lại","Choose again","重新选择")}</button><button type="button" className="endCommit" onClick={finish}>{intent==="event-notice"?tr(p.lang,"Lưu & Đăng thông báo · END","Save & Publish · END","保存并发布 · END"):intent==="gift-create"?tr(p.lang,"Khởi tạo quà · END","Create Gift · END","创建礼物 · END"):intent==="gift-manage"?tr(p.lang,"Lưu quản lý quà · END","Save Gift Changes · END","保存礼物更改 · END"):intent==="room-create"?tr(p.lang,"Tạo room · END","Create Room · END","创建房间 · END"):intent==="room-name"?tr(p.lang,"Lưu tên phòng · END","Save Room Name · END","保存房间名称 · END"):intent==="graphics-overlay"?tr(p.lang,"Apply đồ họa · END","Apply Graphic · END","应用图形 · END"):intent==="profile"?tr(p.lang,"Lưu hồ sơ · END","Save Profile · END","保存资料 · END"):tr(p.lang,"Áp dụng · END","Apply · END","应用 · END")}</button></div>
 </section>
}
