"use client";
import {useEffect,useMemo,useState} from "react";

type Lang="vi"|"en"|"zh";
type Mode="studio-export"|"studio-flash-flow"|"studio-room"|"studio-mixer";
type Props={lang:Lang;mode:Mode;activeId:string;activeLabel:string;actionId?:string;actionLabel?:string;selectedId:string;selectedLabel:string;onCancel:()=>void;onComplete:()=>void};
const tr=(l:Lang,vi:string,en:string,zh:string)=>l==="en"?en:l==="zh"?zh:vi;
function Card({title,children}:{title:string;children:any}){return <div className="semanticCard"><b>{title}</b><div>{children}</div></div>}
function isAuthenticated(){try{return localStorage.getItem("long-authenticated")==="1"||sessionStorage.getItem("long-authenticated")==="1";}catch{return false}}

export default function StudioWorkflowPanel(p:Props){
 const [auth,setAuth]=useState(false);const[status,setStatus]=useState("");const[file,setFile]=useState<File|null>(null);const[source,setSource]=useState("device");const[value,setValue]=useState(50);const[name,setName]=useState("");const[visibility,setVisibility]=useState("public");const[selectedVideo,setSelectedVideo]=useState("");
 const library=useMemo(()=>{try{return JSON.parse(localStorage.getItem("long-event-video-library-v1")||"[]") as Array<{id:string;title:string;url?:string}>}catch{return []}},[]);
 useEffect(()=>setAuth(isAuthenticated()),[]);
 const persistentBlocked=!auth;
 const finish=()=>{setStatus(tr(p.lang,"✓ Hoàn tất · END","✓ Complete · END","✓ 完成 · END"));setTimeout(p.onComplete,450)};
 if(p.mode==="studio-export") return <div className="semanticWorkspace semanticEmbedded studioWorkflow">
  <div className="semanticHead"><div><small>STUDIO · EVENT VIDEO DOWNLOAD</small><h2>{p.selectedLabel}</h2></div><span className="runtimeBadge">{tr(p.lang,"TẢI VIDEO CÓ SẴN","EXISTING VIDEO","已有视频")}</span></div>
  <div className="semanticGrid"><Card title={tr(p.lang,"Video sự kiện","Event video","活动视频")}>
   {!auth?<div className="semanticResult">{tr(p.lang,"Đăng nhập để xem các video sự kiện thuộc tài khoản của bạn. Không dùng ô tải file lên ở bước Xuất video.","Sign in to view event videos owned by your account. Export Video never asks you to upload a file here.","请登录以查看您账户中的活动视频。“导出视频”步骤不会要求在此上传文件。")}</div>:library.length?<select value={selectedVideo} onChange={e=>setSelectedVideo(e.target.value)}><option value="">{tr(p.lang,"Chọn video sự kiện","Choose event video","选择活动视频")}</option>{library.map(v=><option key={v.id} value={v.id}>{v.title}</option>)}</select>:<div className="semanticResult">{tr(p.lang,"Chưa có video sự kiện sẵn sàng trong thư viện runtime.","No event video is currently available in the runtime library.","运行时媒体库中暂无可用活动视频。")}</div>}
  </Card><Card title={tr(p.lang,"Định dạng tải về","Download format","下载格式")}><div className="choiceRow"><span className="statePill">{p.selectedLabel}</span><span className="statePill">{p.actionLabel||tr(p.lang,"Xuất về máy","Download to device","下载到设备")}</span></div><div className="semanticResult">{tr(p.lang,"Luồng đúng: chọn video sự kiện đã có → chọn định dạng → tải về máy.","Correct flow: choose an existing event video → choose a format → download it.","正确流程：选择已有活动视频 → 选择格式 → 下载到设备。")}</div></Card></div>
  <div className="semanticEndRow"><button className="secondaryEnd" onClick={p.onCancel}>{tr(p.lang,"Chọn lại","Choose again","重新选择")}</button><button className="endCommit" disabled={!auth||!selectedVideo} onClick={()=>{const v=library.find(x=>x.id===selectedVideo);if(v?.url){const a=document.createElement('a');a.href=v.url;a.download='';a.click();finish()}else setStatus(tr(p.lang,"Video chưa có URL tải về từ runtime/backend.","The selected video has no downloadable runtime/backend URL yet.","所选视频尚无运行时/后端下载地址。"))}}>{auth?tr(p.lang,"Tải video · END","Download Video · END","下载视频 · END"):tr(p.lang,"Đăng nhập để tải","Sign in to download","登录后下载")}</button></div>{status&&<div className="semanticStatus">{status}</div>}
 </div>;
 if(p.mode==="studio-flash-flow") return <div className="semanticWorkspace semanticEmbedded studioWorkflow">
  <div className="semanticHead"><div><small>STUDIO · FLASH FLOW SOURCE</small><h2>Flash Flow</h2></div><span className="runtimeBadge">{tr(p.lang,"CHỌN NGUỒN TRƯỚC","SOURCE FIRST","先选来源")}</span></div>
  <div className="semanticGrid"><Card title={tr(p.lang,"Nguồn Flash Flow","Flash Flow source","Flash Flow 来源")}><select value={source} onChange={e=>{setSource(e.target.value);setFile(null)}}><option value="device">{tr(p.lang,"Ảnh / video từ máy","Image / video from device","设备中的图片/视频")}</option><option value="event">{tr(p.lang,"Media sự kiện đã có","Existing event media","已有活动媒体")}</option><option value="camera">Camera / Capture</option><option value="url">URL / Stream</option></select>{source==="device"&&<input type="file" accept="image/*,video/*" onChange={e=>setFile(e.target.files?.[0]||null)}/>} {source==="event"&&<div className="semanticResult">{auth?tr(p.lang,"Chọn media từ thư viện sự kiện runtime; không dùng dữ liệu mẫu.","Choose media from the runtime event library; no sample data.","从运行时活动媒体库中选择；不使用样例数据。"):tr(p.lang,"Đăng nhập để dùng media sự kiện của bạn.","Sign in to use your event media.","登录后使用您的活动媒体。")}</div>} {source==="camera"&&<div className="semanticResult">{tr(p.lang,"Runtime sẽ yêu cầu Camera/Capture khi bạn bắt đầu Preview.","Runtime will request Camera/Capture permission when Preview starts.","开始预览时运行时将请求相机/采集权限。")}</div>} {source==="url"&&<input placeholder="https://… / SRT / NDI bridge"/>}</Card><Card title={tr(p.lang,"Flow / Template","Flow / Template","Flow / 模板")}><div className="choiceRow"><span className="statePill">{p.actionLabel||"Flow"}</span><span className="statePill">{p.selectedLabel}</span></div><button type="button" onClick={()=>setStatus(file?tr(p.lang,`Đã nạp ${file.name}. Sẵn sàng Preview.`,`Loaded ${file.name}. Ready to preview.`,`已载入 ${file.name}，可预览。`):source!=="device"?tr(p.lang,"Nguồn đã chọn. Runtime sẽ kiểm tra trước Preview.","Source selected. Runtime will validate before Preview.","已选择来源，运行时将在预览前验证。"):tr(p.lang,"Hãy chọn ảnh/video nguồn trước.","Choose a source image/video first.","请先选择来源图片/视频。"))}>{tr(p.lang,"Nạp nguồn / Preview","Load Source / Preview","载入来源 / 预览")}</button><div className="semanticResult">{status||tr(p.lang,"Không chạy Flash Flow khi chưa có nguồn hợp lệ.","Flash Flow cannot run until a valid source is selected.","未选择有效来源前不能运行 Flash Flow。")}</div></Card></div>
  <div className="semanticEndRow"><button className="secondaryEnd" onClick={p.onCancel}>{tr(p.lang,"Chọn lại","Choose again","重新选择")}</button><button className="endCommit" disabled={source==="device"&&!file} onClick={finish}>{tr(p.lang,"Áp dụng Flow · END","Apply Flow · END","应用 Flow · END")}</button></div>
 </div>;
 if(p.mode==="studio-room") return <div className="semanticWorkspace semanticEmbedded studioWorkflow">
  <div className="semanticHead"><div><small>STUDIO · LIVE ROOM</small><h2>{p.activeLabel}</h2></div><span className="runtimeBadge">{auth?tr(p.lang,"ĐÃ ĐĂNG NHẬP","SIGNED IN","已登录"):tr(p.lang,"CẦN ĐĂNG NHẬP","SIGN-IN REQUIRED","需要登录")}</span></div>
  <div className="semanticGrid"><Card title={tr(p.lang,"Thông tin phòng","Room details","房间信息")}><input value={name} onChange={e=>setName(e.target.value)} placeholder={tr(p.lang,"Tên room / sự kiện","Room / event name","房间/活动名称")}/><select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="public">{tr(p.lang,"Công khai","Public","公开")}</option><option value="private">{tr(p.lang,"Riêng tư","Private","私密")}</option><option value="event">{tr(p.lang,"Theo sự kiện","Event only","仅活动")}</option></select></Card><Card title={tr(p.lang,"Quyền tạo room","Room permission","创建房间权限")}><div className="semanticResult">{auth?tr(p.lang,"Tài khoản đã xác thực có thể tạo và lưu room. Backend sẽ tạo room/session thật khi endpoint room được kết nối.","Authenticated accounts can create and persist rooms. The backend creates the live room/session when the room endpoint is connected.","已认证账户可创建并保存房间；连接房间后端接口后将创建真实房间/会话。") : tr(p.lang,"Bạn chưa đăng nhập. Có thể xem/chuẩn bị cấu hình nhưng không được tạo hoặc lưu room.","You are not signed in. You may review the setup, but cannot create or persist a room.","您尚未登录。可以查看配置，但不能创建或保存房间。")}</div></Card></div>
  <div className="semanticEndRow"><button className="secondaryEnd" onClick={p.onCancel}>{tr(p.lang,"Chọn lại","Choose again","重新选择")}</button><button className="endCommit" disabled={!auth||!name.trim()} onClick={()=>{setStatus(tr(p.lang,"Đã xác nhận cấu hình room. Chờ backend room/session để tạo thật.","Room configuration validated. Waiting for the room/session backend to create it.","房间配置已验证，等待房间/会话后端创建。"));}}>{auth?tr(p.lang,"Tạo room · END","Create Room · END","创建房间 · END"):tr(p.lang,"Đăng nhập để tạo room","Sign in to create room","登录后创建房间")}</button></div>{status&&<div className="semanticStatus">{status}</div>}
 </div>;
 return <div className="semanticWorkspace semanticEmbedded studioWorkflow">
  <div className="semanticHead"><div><small>STUDIO · MIXER RUNTIME</small><h2>{p.actionLabel||p.activeLabel} · {p.selectedLabel}</h2></div><span className="runtimeBadge">{auth?tr(p.lang,"PERSIST ENABLED","PERSIST ENABLED","可持久保存"):tr(p.lang,"TEMP ONLY","TEMP ONLY","仅临时")}</span></div>
  <div className="semanticGrid"><Card title={tr(p.lang,"Điều chỉnh hiện tại","Current adjustment","当前调整")}><label>{p.selectedLabel}<input type="range" min="0" max="100" value={value} onChange={e=>setValue(+e.target.value)}/><span>{value}</span></label><button type="button" onClick={()=>setStatus(tr(p.lang,"Đã áp dụng tạm thời cho phiên hiện tại. Chưa lưu vào tài khoản.","Applied temporarily to the current session. Not saved to the account.","已临时应用到当前会话，尚未保存到账户。"))}>{tr(p.lang,"Áp dụng tạm thời","Apply temporarily","临时应用")}</button></Card><Card title={tr(p.lang,"Lưu cấu hình","Save configuration","保存配置")}><div className="semanticResult">{auth?tr(p.lang,"Có thể lưu preset/cấu hình theo user sau khi backend Mixer persistence được nối.","The preset/config can be saved for the user after Mixer persistence is connected.","连接 Mixer 持久化后可按用户保存预设/配置。") : tr(p.lang,"Chưa đăng nhập: khóa Lưu cấu hình/Preset. Điều chỉnh tạm thời vẫn dùng được nhưng không ghi vào tài khoản.","Not signed in: Save Config/Preset is locked. Temporary adjustments still work but are not written to an account.","未登录：锁定保存配置/预设。临时调整仍可使用，但不会写入账户。")}</div></Card></div>
  {status&&<div className="semanticStatus">{status}</div>}<div className="semanticEndRow"><button className="secondaryEnd" onClick={p.onCancel}>{tr(p.lang,"Chọn lại","Choose again","重新选择")}</button><button className="endCommit" disabled={persistentBlocked} onClick={finish}>{auth?tr(p.lang,"Lưu cấu hình · END","Save Configuration · END","保存配置 · END"):tr(p.lang,"Đăng nhập để lưu","Sign in to save","登录后保存")}</button></div>
 </div>;
}
