"use client";
import {useEffect,useMemo,useState} from "react";
import {useEventSpace} from "@/components/EventSpaceProvider";
import type {RuntimeResult} from "@/lib/eventspace-runtime";

type Lang="vi"|"en"|"zh";
type Mode="studio-export"|"studio-flash-flow"|"studio-room"|"studio-mixer";
type Props={lang:Lang;mode:Mode;activeId:string;activeLabel:string;actionId?:string;actionLabel?:string;selectedId:string;selectedLabel:string;onCancel:()=>void;onComplete:()=>void};
const tr=(l:Lang,vi:string,en:string,zh:string)=>l==="en"?en:l==="zh"?zh:vi;
function Card({title,children}:{title:string;children:any}){return <div className="semanticCard"><b>{title}</b><div>{children}</div></div>}
function isAuthenticated(){try{return localStorage.getItem("long-authenticated")==="1"||sessionStorage.getItem("long-authenticated")==="1";}catch{return false}}

export default function StudioWorkflowPanel(p:Props){
 const {dispatch}=useEventSpace();
 const [auth,setAuth]=useState(false);const[status,setStatus]=useState("");const[file,setFile]=useState<File|null>(null);const[source,setSource]=useState("device");const[value,setValue]=useState(50);const[name,setName]=useState("");const[visibility,setVisibility]=useState("public");const[selectedVideo,setSelectedVideo]=useState("");
 const [previewUrl,setPreviewUrl]=useState("");const[externalUrl,setExternalUrl]=useState("");const[flowStage,setFlowStage]=useState<"idle"|"source-selected"|"preview-ready"|"output-preview-ready">("idle");const[flowResult,setFlowResult]=useState<RuntimeResult|null>(null);
 const library=useMemo(()=>{try{return JSON.parse(localStorage.getItem("long-event-video-library-v1")||"[]") as Array<{id:string;title:string;url?:string}>}catch{return []}},[]);
 useEffect(()=>setAuth(isAuthenticated()),[]);
 useEffect(()=>{if(!file){setPreviewUrl("");return}const url=URL.createObjectURL(file);setPreviewUrl(url);return()=>URL.revokeObjectURL(url)},[file]);
 const persistentBlocked=!auth;
 const finish=()=>{setStatus(tr(p.lang,"✓ Hoàn tất","✓ Complete","✓ 完成"));setTimeout(p.onComplete,450)};
 const eventMedia=library.find(item=>item.id===selectedVideo);
 const activePreviewUrl=source==="device"?previewUrl:source==="event"?eventMedia?.url||"":source==="url"?externalUrl.trim():"";
 const isVideo=source==="device"?Boolean(file?.type.startsWith("video/")):/\.(mp4|webm|mov|m3u8)(\?|$)/i.test(activePreviewUrl);
 function resetFlow(nextSource=source){setSource(nextSource);setFile(null);setSelectedVideo("");setExternalUrl("");setFlowStage("idle");setFlowResult(null);setStatus("")}
 function chooseDeviceFile(next:File|null){setFile(next);setFlowResult(null);setFlowStage(next?"source-selected":"idle");setStatus(next?tr(p.lang,`Đã chọn ${next.name}.`,`Selected ${next.name}.`,`已选择 ${next.name}。`):"")}
 function loadFlowPreview(){
  if(source==="camera"){setStatus(tr(p.lang,"Camera/Capture cần mở qua tác vụ Xem camera trước khi đưa vào Flash Flow.","Open Camera/Capture with View Camera before sending it to Flash Flow.","请先通过查看相机任务打开相机/采集，再发送到 Flash Flow。"));return}
  if(!activePreviewUrl){setStatus(source==="event"&&!auth?tr(p.lang,"Đăng nhập và chọn media sự kiện trước.","Sign in and choose event media first.","请先登录并选择活动媒体。"):tr(p.lang,"Hãy chọn nguồn ảnh/video hợp lệ trước.","Choose a valid image/video source first.","请先选择有效的图片/视频来源。"));return}
  const mediaName=file?.name||eventMedia?.title||activePreviewUrl;
  const result=dispatch({id:`studio-flash-preview:${Date.now().toString(36)}`,area:"studio.broadcast",action:"create-flash-flow-preview",label:mediaName,intent:"flash-flow-preview",source:source==="device"?"device":"ui",confirmed:true,inputs:{source,mediaName,mediaUrl:source==="device"?"local-object-url":activePreviewUrl}});
  setFlowResult(result);
  if(result.flashArtifact){setFlowStage("preview-ready");setStatus(tr(p.lang,"Đã dựng bản xem trước từ nguồn thật. Kiểm tra rồi áp dụng Flow.","A real-source preview is ready. Review it, then apply Flow.","已从真实来源生成预览，请检查后应用 Flow。"))}else setStatus(tr(p.lang,"Runtime chưa tạo được bản xem trước.","Runtime could not create a preview.","运行时无法生成预览。"));
 }
 function applyFlow(){
  if(flowStage!=="preview-ready"||!activePreviewUrl){setStatus(tr(p.lang,"Cần có bản xem trước hợp lệ trước khi áp dụng Flow.","A valid preview is required before applying Flow.","应用 Flow 前需要有效预览。"));return}
  const mediaName=file?.name||eventMedia?.title||activePreviewUrl;
  const result=dispatch({id:`studio-flash-output:${Date.now().toString(36)}`,area:"studio.broadcast",action:"apply-flash-flow-output",label:mediaName,intent:"flash-flow-output-preview",source:source==="device"?"device":"ui",confirmed:true,inputs:{source,mediaName,outcome:"output-preview"}});
  setFlowResult(result);
  if(result.flashArtifact){setFlowStage("output-preview-ready");setStatus(tr(p.lang,"Đã tạo bản xem trước đầu ra theo Pixel Execution Plan. Đây chưa phải file video đã xuất.","Output preview created from the Pixel Execution Plan. This is not an exported video file yet.","已按像素执行计划生成输出预览；这还不是已导出的视频文件。"))}else setStatus(tr(p.lang,"Chưa có artifact đầu ra; Flow chưa được đánh dấu hoàn tất.","No output artifact exists; Flow was not marked complete.","没有输出产物；Flow 未标记为完成。"));
 }
 if(p.mode==="studio-export") return <div className="semanticWorkspace semanticEmbedded studioWorkflow">
  <div className="semanticHead"><div><small>STUDIO · EVENT VIDEO DOWNLOAD</small><h2>{p.selectedLabel}</h2></div><span className="runtimeBadge">{tr(p.lang,"TẢI VIDEO CÓ SẴN","EXISTING VIDEO","已有视频")}</span></div>
  <div className="semanticGrid"><Card title={tr(p.lang,"Video sự kiện","Event video","活动视频")}>
   {!auth?<div className="semanticResult">{tr(p.lang,"Đăng nhập để xem các video sự kiện thuộc tài khoản của bạn. Không dùng ô tải file lên ở bước Xuất video.","Sign in to view event videos owned by your account. Export Video never asks you to upload a file here.","请登录以查看您账户中的活动视频。“导出视频”步骤不会要求在此上传文件。")}</div>:library.length?<select value={selectedVideo} onChange={e=>setSelectedVideo(e.target.value)}><option value="">{tr(p.lang,"Chọn video sự kiện","Choose event video","选择活动视频")}</option>{library.map(v=><option key={v.id} value={v.id}>{v.title}</option>)}</select>:<div className="semanticResult">{tr(p.lang,"Chưa có video sự kiện sẵn sàng trong thư viện runtime.","No event video is currently available in the runtime library.","运行时媒体库中暂无可用活动视频。")}</div>}
  </Card><Card title={tr(p.lang,"Định dạng tải về","Download format","下载格式")}><div className="choiceRow"><span className="statePill">{p.selectedLabel}</span><span className="statePill">{p.actionLabel||tr(p.lang,"Xuất về máy","Download to device","下载到设备")}</span></div><div className="semanticResult">{tr(p.lang,"Luồng đúng: chọn video sự kiện đã có → chọn định dạng → tải về máy.","Correct flow: choose an existing event video → choose a format → download it.","正确流程：选择已有活动视频 → 选择格式 → 下载到设备。")}</div></Card></div>
  <div className="semanticEndRow"><button data-action-id="pro.components.studioworkflowpanel.button.001" className="secondaryEnd" onClick={p.onCancel}>{tr(p.lang,"Chọn lại","Choose again","重新选择")}</button><button data-action-id="pro.components.studioworkflowpanel.button.002" className="endCommit" disabled={!auth||!selectedVideo} onClick={()=>{const v=library.find(x=>x.id===selectedVideo);if(v?.url){const a=document.createElement('a');a.href=v.url;a.download='';a.click();finish()}else setStatus(tr(p.lang,"Video chưa có URL tải về từ runtime/backend.","The selected video has no downloadable runtime/backend URL yet.","所选视频尚无运行时/后端下载地址。"))}}>{auth?tr(p.lang,"Tải video","Download Video","下载视频"):tr(p.lang,"Đăng nhập để tải","Sign in to download","登录后下载")}</button></div>{status&&<div className="semanticStatus">{status}</div>}
 </div>;
 if(p.mode==="studio-flash-flow") return <div className="semanticWorkspace semanticEmbedded studioWorkflow">
  <div className="semanticHead"><div><small>STUDIO · FLASH FLOW SOURCE</small><h2>Flash Flow</h2></div><span className="runtimeBadge">{tr(p.lang,"CHỌN NGUỒN TRƯỚC","SOURCE FIRST","先选来源")}</span></div>
  <div className="semanticGrid"><Card title={tr(p.lang,"Nguồn Flash Flow","Flash Flow source","Flash Flow 来源")}><select value={source} onChange={e=>resetFlow(e.target.value)}><option value="device">{tr(p.lang,"Ảnh / video từ máy","Image / video from device","设备中的图片/视频")}</option><option value="event">{tr(p.lang,"Media sự kiện đã có","Existing event media","已有活动媒体")}</option><option value="camera">Camera / Capture</option><option value="url">URL / Stream</option></select>{source==="device"&&<input type="file" accept="image/*,video/*" onChange={e=>chooseDeviceFile(e.target.files?.[0]||null)}/>} {source==="event"&&(auth&&library.length?<select value={selectedVideo} onChange={e=>{setSelectedVideo(e.target.value);setFlowStage(e.target.value?"source-selected":"idle");setFlowResult(null)}}><option value="">{tr(p.lang,"Chọn media sự kiện","Choose event media","选择活动媒体")}</option>{library.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select>:<div className="semanticResult">{auth?tr(p.lang,"Chưa có media sự kiện có URL runtime.","No event media with a runtime URL is available.","没有带运行时 URL 的活动媒体。"):tr(p.lang,"Đăng nhập để dùng media sự kiện của bạn.","Sign in to use your event media.","登录后使用您的活动媒体。")}</div>)} {source==="camera"&&<div className="semanticResult">{tr(p.lang,"Mở Xem camera trước; Flash Flow không báo hoàn tất nếu chưa nhận MediaStream.","Open View Camera first; Flash Flow will not report completion without a MediaStream.","请先打开查看相机；未收到媒体流时 Flash Flow 不会报告完成。")}</div>} {source==="url"&&<input value={externalUrl} onChange={e=>{setExternalUrl(e.target.value);setFlowStage(e.target.value.trim()?"source-selected":"idle");setFlowResult(null)}} placeholder="https://… / stream"/>}</Card><Card title={tr(p.lang,"Flow / Template","Flow / Template","Flow / 模板")}><div className="choiceRow"><span className="statePill">{p.actionLabel||"Flow"}</span><span className="statePill">{p.selectedLabel}</span><span className="statePill">{flowStage.toUpperCase().replaceAll("-","_")}</span></div><button data-action-id="pro.components.studioworkflowpanel.button.003" type="button" data-runtime-ignore="true" onClick={loadFlowPreview}>{tr(p.lang,"Nạp nguồn / Xem trước","Load Source / Preview","载入来源 / 预览")}</button><div className="semanticResult">{status||tr(p.lang,"Chọn nguồn thật để tạo bản xem trước.","Choose a real source to create a preview.","选择真实来源以生成预览。")}</div></Card></div>
  {(flowStage==="preview-ready"||flowStage==="output-preview-ready")&&activePreviewUrl&&<section className={`flashFlowResult ${flowStage}`} aria-live="polite"><div className="flashFlowResultHead"><div><small>{flowStage==="output-preview-ready"?"OUTPUT_PREVIEW_READY":"PREVIEW_READY"}</small><b>{file?.name||eventMedia?.title||tr(p.lang,"Nguồn URL","URL source","URL 来源")}</b></div><span>{flowResult?.pixelPlan?.target||"—"} · {flowResult?.pixelPlan?.fps||"—"} FPS</span></div><div className="flashFlowMedia">{isVideo?<video src={activePreviewUrl} controls playsInline preload="metadata"/>:<img src={activePreviewUrl} alt={tr(p.lang,"Bản xem trước nguồn Flash Flow","Flash Flow source preview","Flash Flow 来源预览")}/>} {flowStage==="output-preview-ready"&&<div className="pixelGovernorOverlay" aria-hidden="true"><i/><i/><i/></div>}</div><div className="flashFlowMeta"><span>Pixel Governor {flowResult?.pixelPlan?.version||"FPG-1.0"}</span><span>{flowResult?.pixelPlan?.codecProfile||"local"}</span><span>{flowStage==="output-preview-ready"?tr(p.lang,"Bản xem trước đầu ra","Output preview","输出预览"):tr(p.lang,"Nguồn gốc","Original source","原始来源")}</span></div></section>}
  <div className="semanticEndRow"><button data-action-id="pro.components.studioworkflowpanel.button.004" className="secondaryEnd" onClick={p.onCancel}>{tr(p.lang,"Chọn lại","Choose again","重新选择")}</button>{flowStage==="output-preview-ready"?<button data-action-id="pro.components.studioworkflowpanel.button.005" className="endCommit" data-runtime-ignore="true" onClick={finish}>{tr(p.lang,"Xác nhận kết quả","Confirm Result","确认结果")}</button>:<button data-action-id="pro.components.studioworkflowpanel.button.006" className="endCommit" data-runtime-ignore="true" disabled={flowStage!=="preview-ready"} onClick={applyFlow}>{tr(p.lang,"Áp dụng Flow","Apply Flow","应用 Flow")}</button>}</div>
 </div>;
 if(p.mode==="studio-room") return <div className="semanticWorkspace semanticEmbedded studioWorkflow">
  <div className="semanticHead"><div><small>STUDIO · LIVE ROOM</small><h2>{p.activeLabel}</h2></div><span className="runtimeBadge">{auth?tr(p.lang,"ĐÃ ĐĂNG NHẬP","SIGNED IN","已登录"):tr(p.lang,"CẦN ĐĂNG NHẬP","SIGN-IN REQUIRED","需要登录")}</span></div>
  <div className="semanticGrid"><Card title={tr(p.lang,"Thông tin phòng","Room details","房间信息")}><input value={name} onChange={e=>setName(e.target.value)} placeholder={tr(p.lang,"Tên room / sự kiện","Room / event name","房间/活动名称")}/><select value={visibility} onChange={e=>setVisibility(e.target.value)}><option value="public">{tr(p.lang,"Công khai","Public","公开")}</option><option value="private">{tr(p.lang,"Riêng tư","Private","私密")}</option><option value="event">{tr(p.lang,"Theo sự kiện","Event only","仅活动")}</option></select></Card><Card title={tr(p.lang,"Quyền tạo room","Room permission","创建房间权限")}><div className="semanticResult">{auth?tr(p.lang,"Tài khoản đã xác thực có thể tạo và lưu room. Backend sẽ tạo room/session thật khi endpoint room được kết nối.","Authenticated accounts can create and persist rooms. The backend creates the live room/session when the room endpoint is connected.","已认证账户可创建并保存房间；连接房间后端接口后将创建真实房间/会话。") : tr(p.lang,"Bạn chưa đăng nhập. Có thể xem/chuẩn bị cấu hình nhưng không được tạo hoặc lưu room.","You are not signed in. You may review the setup, but cannot create or persist a room.","您尚未登录。可以查看配置，但不能创建或保存房间。")}</div></Card></div>
  <div className="semanticEndRow"><button data-action-id="pro.components.studioworkflowpanel.button.007" className="secondaryEnd" onClick={p.onCancel}>{tr(p.lang,"Chọn lại","Choose again","重新选择")}</button><button data-action-id="pro.components.studioworkflowpanel.button.008" className="endCommit" disabled={!auth||!name.trim()} onClick={()=>{setStatus(tr(p.lang,"Đã xác nhận cấu hình room. Chờ backend room/session để tạo thật.","Room configuration validated. Waiting for the room/session backend to create it.","房间配置已验证，等待房间/会话后端创建。"));}}>{auth?tr(p.lang,"Tạo room","Create Room","创建房间"):tr(p.lang,"Đăng nhập để tạo room","Sign in to create room","登录后创建房间")}</button></div>{status&&<div className="semanticStatus">{status}</div>}
 </div>;
 return <div className="semanticWorkspace semanticEmbedded studioWorkflow">
  <div className="semanticHead"><div><small>STUDIO · MIXER RUNTIME</small><h2>{p.actionLabel||p.activeLabel} · {p.selectedLabel}</h2></div><span className="runtimeBadge">{auth?tr(p.lang,"PERSIST ENABLED","PERSIST ENABLED","可持久保存"):tr(p.lang,"TEMP ONLY","TEMP ONLY","仅临时")}</span></div>
  <div className="semanticGrid"><Card title={tr(p.lang,"Điều chỉnh hiện tại","Current adjustment","当前调整")}><label>{p.selectedLabel}<input type="range" min="0" max="100" value={value} onChange={e=>setValue(+e.target.value)}/><span>{value}</span></label><button data-action-id="pro.components.studioworkflowpanel.button.009" type="button" onClick={()=>setStatus(tr(p.lang,"Đã áp dụng tạm thời cho phiên hiện tại. Chưa lưu vào tài khoản.","Applied temporarily to the current session. Not saved to the account.","已临时应用到当前会话，尚未保存到账户。"))}>{tr(p.lang,"Áp dụng tạm thời","Apply temporarily","临时应用")}</button></Card><Card title={tr(p.lang,"Lưu cấu hình","Save configuration","保存配置")}><div className="semanticResult">{auth?tr(p.lang,"Có thể lưu preset/cấu hình theo user sau khi backend Mixer persistence được nối.","The preset/config can be saved for the user after Mixer persistence is connected.","连接 Mixer 持久化后可按用户保存预设/配置。") : tr(p.lang,"Chưa đăng nhập: khóa Lưu cấu hình/Preset. Điều chỉnh tạm thời vẫn dùng được nhưng không ghi vào tài khoản.","Not signed in: Save Config/Preset is locked. Temporary adjustments still work but are not written to an account.","未登录：锁定保存配置/预设。临时调整仍可使用，但不会写入账户。")}</div></Card></div>
  {status&&<div className="semanticStatus">{status}</div>}<div className="semanticEndRow"><button data-action-id="pro.components.studioworkflowpanel.button.010" className="secondaryEnd" onClick={p.onCancel}>{tr(p.lang,"Chọn lại","Choose again","重新选择")}</button><button data-action-id="pro.components.studioworkflowpanel.button.011" className="endCommit" disabled={persistentBlocked} onClick={finish}>{auth?tr(p.lang,"Lưu cấu hình","Save Configuration","保存配置"):tr(p.lang,"Đăng nhập để lưu","Sign in to save","登录后保存")}</button></div>
 </div>;
}
