"use client";
import {useMemo,useState} from "react";
import type {Lang} from "@/lib/navigation";

type Props={lang:Lang;onBack:()=>void;onDone:()=>void};
const templates=[
 {id:"event-announce",vi:"Thông báo sự kiện",en:"Event announcement"},
 {id:"product-card",vi:"Giới thiệu sản phẩm",en:"Product showcase"},
 {id:"live-intro",vi:"Intro livestream",en:"Livestream intro"},
 {id:"short-recap",vi:"Recap ngắn",en:"Short recap"},
];
export default function TemplateVideoBuilder({lang,onBack,onDone}:Props){
 const vi=lang==="vi"; const [tpl,setTpl]=useState(templates[0].id); const[files,setFiles]=useState<File[]>([]); const[title,setTitle]=useState(""); const[rendered,setRendered]=useState(false);const[query,setQuery]=useState("event background");const[assets,setAssets]=useState<any[]>([]);const[selectedAsset,setSelectedAsset]=useState<any|null>(null);const[status,setStatus]=useState("");
 const names=useMemo(()=>files.map(f=>f.name),[files]);
 async function searchAssets(){setStatus(vi?"Đang tìm nguồn miễn phí có license…":"Searching licensed free resources…");const result=await fetch(`/api/assets/search?q=${encodeURIComponent(query)}`).then(r=>r.json()).catch(()=>({ok:false,assets:[]}));setAssets(result.assets||[]);setStatus(result.ok?"":(vi?"Nguồn ngoài tạm thời không khả dụng; hãy dùng file trên thiết bị.":"External source unavailable; use a device file."))}
 async function createVideo(){setRendered(false);setStatus(vi?"Đang gửi job dựng video…":"Submitting render job…");const result=await fetch("/api/runtime/execute",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({invocationId:`render:${crypto.randomUUID()}`,actionId:"scene.template.render",executor:"job",adapter:"media-render-worker",input:{template:tpl,title,files:files.map(f=>f.name),externalAsset:selectedAsset&&{url:selectedAsset.url,license:selectedAsset.license,sourceUrl:selectedAsset.sourceUrl,attribution:selectedAsset.attribution}}})}).then(r=>r.json()).catch(()=>({ok:false,code:"RENDER_UNAVAILABLE"}));if(result.ok&&result.receipt?.signature){setRendered(true);setStatus(vi?"Video đã tạo và có receipt.":"Video created with a verified receipt.")}else setStatus(vi?`Chưa tạo video: ${result.code||"thiếu render worker/receipt"}`:`Video not created: ${result.code||"render worker/receipt missing"}`)}
 return <section className="navWorkspace specializedPanel">
  <div className="workspaceCrumbs"><button data-action-id="pro.components.templatevideobuilder.button.001" type="button" className="backKey" onClick={onBack}>← Back</button><button data-action-id="pro.components.templatevideobuilder.button.002" type="button" className="crumbKey selected">{vi?"Tạo video":"Create Video"}</button><button data-action-id="pro.components.templatevideobuilder.button.003" type="button" className="crumbKey selected tree5Crumb">{vi?"Từ mẫu":"From Template"}</button></div>
  <div className="specialHead"><div><span>SPECIALIZED CONTENT</span><h2>{vi?"Dựng video từ mẫu":"Template Video Builder"}</h2></div><b className={`statePill ${rendered?"live":"ready"}`}>{rendered?(vi?"ĐÃ TẠO":"CREATED"):(vi?"SẴN SÀNG":"READY")}</b></div>
  <div className="specialGrid">
   <label><span>{vi?"1. Chọn template":"1. Choose template"}</span><select value={tpl} onChange={e=>{setTpl(e.target.value);setRendered(false)}}>{templates.map(t=><option key={t.id} value={t.id}>{vi?t.vi:t.en}</option>)}</select></label>
   <label><span>{vi?"2. Tiêu đề video":"2. Video title"}</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder={vi?"Ví dụ: Sự kiện cuối tuần":"Example: Weekend Event"}/></label>
   <label className="wide"><span>{vi?"3. Chọn ảnh/video từ máy":"3. Pick photos/videos from device"}</span><input type="file" accept="image/*,video/*" multiple onChange={e=>{setFiles(Array.from(e.target.files||[]));setRendered(false)}}/><small>{names.length?names.join(" · "):(vi?"Chưa chọn nội dung":"No media selected")}</small></label>
   <div className="templatePreview wide"><b>{vi?"Hoặc tìm ảnh mẫu bên ngoài":"Or find external sample images"}</b><div className="aiComposer"><input value={query} onChange={e=>setQuery(e.target.value)}/><button data-action-id="pro.scene.assets.search" type="button" onClick={searchAssets}>{vi?"Tìm nguồn":"Search"}</button></div><div className="stickerGrid">{assets.map(asset=><button data-action-id={`pro.scene.assets.select.${asset.id}`} type="button" key={asset.id} onClick={()=>setSelectedAsset(asset)} className={selectedAsset?.id===asset.id?"priority":""}><img src={asset.previewUrl} alt="" loading="lazy"/><small>{asset.license} · {asset.creator}</small></button>)}</div>{selectedAsset&&<small>{selectedAsset.attribution} · <a href={selectedAsset.sourceUrl} target="_blank" rel="noreferrer">Source/license evidence</a></small>}{status&&<div className="connectResult">{status}</div>}</div>
   <div className="templatePreview wide"><b>{vi?"Preview template":"Template preview"}</b><span>{vi?"Template sẽ tự đặt media vào các slot dựng sẵn; không cần camera/microphone permission.":"Selected media will be placed into predefined template slots; no camera/microphone permission is required."}</span><div className="previewMock">{templates.find(t=>t.id===tpl)?.[vi?"vi":"en"]} · {files.length} media</div></div>
  </div>
  <div className="endCommitRow"><button data-action-id="pro.components.templatevideobuilder.button.004" type="button" className="secondaryEnd" onClick={onBack}>{vi?"Chọn lại":"Choose again"}</button><button data-action-id="pro.components.templatevideobuilder.button.005" data-runtime-ignore="true" type="button" className="endCommit" disabled={!files.length&&!selectedAsset} onClick={createVideo}>{rendered?(vi?"✓ Video có receipt":"✓ Verified video"):(vi?"Tạo video":"Create video")}</button>{rendered&&<button data-action-id="pro.components.templatevideobuilder.button.006" type="button" className="endCommit" onClick={onDone}>{vi?"Đưa vào Phát sóng":"Send to Broadcast"}</button>}</div>
 </section>
}
