export type Lang="vi"|"en"|"zh";
export type Localized={vi:string;en:string;zh:string};
export type NavChild={id:string;label:Localized};
export type CoreItem={id:string;label:Localized;children:NavChild[]};
const L=(vi:string,en:string,zh:string):Localized=>({vi,en,zh});
const C=(id:string,vi:string,en:string,zh:string):NavChild=>({id,label:L(vi,en,zh)});
export const core={
 home:[
  {id:"home.quickview",label:L("Xem nhanh","Quick View","快速查看"),children:[C("news","Bản tin","News","资讯"),C("video","Video","Video","视频"),C("events","Sự kiện","Events","活动"),C("following","Đang theo dõi","Following","正在关注"),C("recommended","Gợi ý cho tôi","For You","为你推荐")]},
  {id:"home.myai",label:L("AI của tôi","My AI","我的 AI"),children:[C("ai-flash","AI Flash","AI Flash","AI Flash"),C("my-ai","AI của tôi","My AI","我的 AI"),C("studio-ai","AI Phòng Thu","Studio AI","演播室 AI"),C("lsl","Long Scene Language","Long Scene Language","Long 场景语言"),C("cinematic","Kỹ năng điện ảnh","Cinematic Skills","电影技能"),C("ai-settings","Cài đặt AI","AI Settings","AI 设置")]},
  {id:"home.connect",label:L("Kết Nối","Connect","连接"),children:[C("ai","AI","AI","AI"),C("apps","Ứng dụng","Apps","应用"),C("devices","Thiết bị","Devices","设备"),C("storage","Storage","Storage","存储"),C("wallet","Wallet","Wallet","钱包"),C("custom","Custom API","Custom API","自定义 API")]},
  {id:"home.quickcreate",label:L("Tạo nhanh","Quick Create","快速创建"),children:[C("notification","Thông báo","Announcement","通知"),C("event","Sự kiện","Event","活动"),C("flash-idle","Flash Idle Video","Flash Idle Video","Flash 待机视频"),C("tvc","TVC","TVC","TVC"),C("flash-training","Flash Training","Flash Training","Flash 训练"),C("post","Bài đăng nhanh","Quick Post","快速发布")]},
 ],
 studio:[
  {id:"studio.broadcast",label:L("Phát Sóng","Broadcast","直播"),children:[C("preview","Xem trước","Preview","预览"),C("camera","Camera","Camera","相机"),C("microphone","Micro","Microphone","麦克风"),C("audio","Mix Âm Thanh","Audio Mix","混音"),C("effects","Hiệu Ứng","Effects","特效"),C("input","Thiết Bị Đầu Vào","Input Devices","输入设备"),C("external","App Ngoài","External Apps","外部应用"),C("tv","Video Output / Tivi","Video Output / TV","视频输出 / 电视"),C("flow","Flash Flow","Flash Flow","Flash Flow"),C("record","Render/Record","Render / Record","渲染 / 录制")]},
  {id:"studio.room",label:L("Đặt tên phòng","Room Setup","房间设置"),children:[C("name","Tên phòng","Room Name","房间名称"),C("topic","Chủ đề","Topic","主题"),C("code","Mã phòng","Room Code","房间码"),C("qr","QR vào phòng","Join QR","加入二维码"),C("owner","BTC / Chủ phòng","Organizer / Owner","主办方 / 房主"),C("guests","Khách mời","Guests","嘉宾"),C("audience","Khán giả","Audience","观众"),C("access","Quyền truy cập","Access","访问权限"),C("schedule","Lịch phòng","Schedule","房间日程"),C("status","Trạng thái phòng","Room Status","房间状态")]},
  {id:"studio.chat",label:L("Chat room","Chat Room","聊天室"),children:[C("messages","Tin nhắn","Messages","消息"),C("images","Ảnh","Images","图片"),C("videos","Video","Video","视频"),C("files","File ≤ 3MB","File ≤ 3MB","文件 ≤ 3MB"),C("mention","Mention","Mention","提及"),C("notice","Thông báo phòng","Room Notices","房间通知"),C("private","Tin nhắn riêng","Private Messages","私信"),C("history","Lịch sử chat","Chat History","聊天记录"),C("moderation","Quản lý chat","Chat Moderation","聊天管理")]},
 ],
 store:[
  {id:"store.orders",label:L("Quản Lý Đơn","Orders","订单管理"),children:[C("buy","Đơn mua","Purchases","购买订单"),C("sell","Đơn bán","Sales Orders","销售订单"),C("unpaid","Chờ thanh toán","Awaiting Payment","待付款"),C("paid","Đã thanh toán","Paid","已付款"),C("processing","Đang xử lý","Processing","处理中"),C("shipping","Đang giao","Shipping","配送中"),C("done","Hoàn tất","Completed","已完成"),C("refund","Hủy / Hoàn tiền","Cancel / Refund","取消 / 退款"),C("search","Tra cứu đơn","Find Order","查询订单"),C("detail","Chi tiết đơn","Order Detail","订单详情")]},
  {id:"store.sales",label:L("Bán Hàng","Sell","销售"),children:[C("create-store","Khởi tạo Store","Create Store","创建商店"),C("product","Đăng/Tạo sản phẩm","Create Product","创建商品"),C("price","Giá bán","Price","价格"),C("policy","Chính sách bán","Sales Policy","销售政策"),C("promo","Khuyến mại","Promotion","促销"),C("media","Ảnh/Video sản phẩm","Product Media","商品媒体"),C("publish","Lên kệ","Publish","上架"),C("unpublish","Gỡ khỏi kệ","Unpublish","下架"),C("public-store","Store public","Public Store","公开商店"),C("stats","Thống kê bán","Sales Analytics","销售统计")]},
  {id:"store.inventory",label:L("Kho Hàng","Inventory","库存"),children:[C("list","Danh sách hàng","Inventory List","库存列表"),C("sku","SKU","SKU","SKU"),C("stock","Tồn kho","Stock","库存量"),C("in","Nhập kho","Stock In","入库"),C("out","Xuất kho","Stock Out","出库"),C("reserve","Giữ hàng","Reserve","预留"),C("checkout","Trừ hàng sau checkout","Deduct after Checkout","结账后扣减"),C("low","Cảnh báo sắp hết","Low Stock Alert","低库存提醒"),C("history","Lịch sử tồn kho","Inventory History","库存历史")]},
  {id:"store.shopping",label:L("Shopping","Shopping","购物"),children:[C("all","Tất cả sản phẩm","All Products","全部商品"),C("category","Danh mục","Categories","分类"),C("search","Tìm kiếm","Search","搜索"),C("featured","Sản phẩm nổi bật","Featured","精选"),C("new","Sản phẩm mới","New Arrivals","新品"),C("promo","Khuyến mại","Promotions","促销"),C("detail","Chi tiết sản phẩm","Product Detail","商品详情"),C("cart","Giỏ hàng","Cart","购物车"),C("checkout","Checkout","Checkout","结账"),C("follow","Theo dõi sản phẩm","Watch Product","关注商品")]},
 ],
 me:[
  {id:"me.profile",label:L("Hồ sơ","Profile","个人资料"),children:[C("personal","Thông tin cá nhân","Personal Info","个人信息"),C("avatar","Ảnh đại diện","Avatar","头像"),C("account","Tài khoản","Account","账户"),C("contact","Liên hệ","Contact","联系方式"),C("points","Long Point","Long Point","Long 积分"),C("level","Cấp độ","Level","等级"),C("my-ai","AI của tôi","My AI","我的 AI"),C("activity","Lịch sử hoạt động","Activity","活动记录"),C("report","Báo cáo cá nhân","Personal Report","个人报告"),C("money","Thu/Chi của tôi","My Income / Expense","我的收支")]},
  {id:"me.settings",label:L("Cài Đặt","Settings","设置"),children:[C("theme","Giao diện / Theme","Appearance / Theme","外观 / 主题"),C("language","Ngôn ngữ","Language","语言"),C("sound","Âm thanh","Sound","声音"),C("security","Bảo mật","Security","安全"),C("privacy","Quyền riêng tư","Privacy","隐私"),C("permissions","Quyền thiết bị","Device Permissions","设备权限"),C("media-permissions","Camera/Micro","Camera / Microphone","相机 / 麦克风"),C("notification","Thông báo","Notifications","通知"),C("media","Media","Media","媒体"),C("network","Mạng","Network","网络"),C("devices","Thiết bị đăng nhập","Signed-in Devices","登录设备")]},
  {id:"me.notifications",label:L("Thông báo","Notifications","通知"),children:[C("system","Hệ thống","System","系统"),C("event","Nhắc lịch sự kiện","Event Reminders","活动提醒"),C("studio","Phòng Thu","Studio","演播室"),C("store","Store / Đơn hàng","Store / Orders","商店 / 订单"),C("ai-confirm","AI xin xác nhận","AI Confirmation","AI 请求确认"),C("ai-done","AI hoàn thành tác vụ","AI Completed","AI 已完成"),C("ai-report","Báo cáo AI","AI Reports","AI 报告"),C("security","Cảnh báo bảo mật","Security Alerts","安全警报"),C("mention","Mention / Chat","Mention / Chat","提及 / 聊天"),C("unread","Chưa đọc","Unread","未读"),C("history","Lịch sử thông báo","Notification History","通知历史")]},
 ]
} satisfies Record<string,CoreItem[]>;
export function label(x:Localized,lang:Lang){return x[lang]||x.vi}
