import {NextResponse} from "next/server";
import {LONG_TRACKS} from "@/core/audio-engine";
type Ext={id?:string;title:string;streamUrl:string;pageUrl?:string;source:"soundcloud"|"zing";mood?:string[]};
type Candidate={id:string;title:string;streamUrl:string;pageUrl?:string;source:string;mood:string[]};
function parse(raw:string|undefined,source:"soundcloud"|"zing"):Ext[]{if(!raw)return[];try{const v=JSON.parse(raw);if(!Array.isArray(v))return[];return v.filter(x=>x&&typeof x.title==="string"&&typeof x.streamUrl==="string").map((x,i)=>({id:x.id||`${source}-${i+1}`,title:x.title,streamUrl:x.streamUrl,pageUrl:x.pageUrl,source,mood:Array.isArray(x.mood)?x.mood:[]}))}catch{return[]}}
function weekSeed(){const d=new Date();const start=Date.UTC(d.getUTCFullYear(),0,1);return Math.floor((d.getTime()-start)/604800000)}
function candidates():Candidate[]{const sc=parse(process.env.SOUNDCLOUD_TRACKS_JSON,"soundcloud");const zg=parse(process.env.ZING_TRACKS_JSON,"zing");const ext=[...sc,...zg].map(x=>({id:x.id!,title:x.title,streamUrl:x.streamUrl,pageUrl:x.pageUrl,source:x.source,mood:x.mood||[]}));const local=LONG_TRACKS.map(t=>({id:t.id,title:t.title,streamUrl:t.src,source:t.source,mood:t.mood}));return [...ext,...local]}
function fallbackRank(all:Candidate[],likes:string[]){const seed=weekSeed();return [...all].sort((a,b)=>{const al=likes.includes(a.id)?-10:0, bl=likes.includes(b.id)?-10:0;const ah=(a.id.split("").reduce((n,c)=>n+c.charCodeAt(0),0)+seed)%97;const bh=(b.id.split("").reduce((n,c)=>n+c.charCodeAt(0),0)+seed)%97;return (al+ah)-(bl+bh)}).slice(0,10)}
async function aiRank(all:Candidate[],likes:string[]){const key=process.env.OPENAI_API_KEY;if(!key||all.length<2)return null;const model=process.env.OPENAI_MODEL;if(!model)return null;const compact=all.map(x=>({id:x.id,title:x.title,source:x.source,mood:x.mood}));const r=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${key}`},body:JSON.stringify({model,messages:[{role:"system",content:"Rank a weekly background-music playlist for a productivity/event app. Return ONLY a JSON array of up to 10 candidate ids, no prose. Prefer user-liked tracks, variety, low-fatigue listening, and configured external candidates which represent current authorized trend feeds."},{role:"user",content:JSON.stringify({likedIds:likes,candidates:compact})}],temperature:.25})});if(!r.ok)return null;const j=await r.json();const text=j.choices?.[0]?.message?.content||"";try{const ids=JSON.parse(text);if(!Array.isArray(ids))return null;const map=new Map(all.map(x=>[x.id,x]));const ranked=ids.map((id:string)=>map.get(id)).filter(Boolean) as Candidate[];return ranked.length?ranked.slice(0,10):null}catch{return null}}
function payload(playlist:Candidate[],mode:string){return {ok:true,week:weekSeed(),refresh:"weekly",selectionMode:mode,generatedAt:new Date().toISOString(),playlist,policy:{soundcloud:"authorized playback only",zing:"authorized playback only",fallback:"5 original Long Ambient tracks"}}}
export async function GET(){const all=candidates();return NextResponse.json(payload(fallbackRank(all,[]),"weekly-fallback"))}
export async function POST(req:Request){const body=await req.json().catch(()=>({}));const likes=Array.isArray(body?.likes)?body.likes.map(String).slice(-30):[];const all=candidates();const ranked=await aiRank(all,likes).catch(()=>null);return NextResponse.json(payload(ranked||fallbackRank(all,likes),ranked?"ai-weekly":"weekly-fallback"))}
